### ISSUE TITLE
Gutenberg 6.5 Gallery additional class required to omit UL margin:

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#100]
Add this selector:

`blocks-gallery-grid`

https://github.com/tomusborne/generatepress/blob/e3baba60b8bc53ba52950b953c40eea1c164dfb8/style.css#L1329-L1331

**Comment by tomusborne** [comment]
Fixed in 2.4: https://github.com/tomusborne/generatepress/commit/a7853ca1c8053656b7898bfcd0207d19c6401fe2

Thanks!
