### ISSUE TITLE
Copyright as Widget

### ISSUE THREAD

**Issue by BigAndini** [tomusborne/generatepress#102]
Hey Tom,

I really enjoy your theme and it's pretty nice to build websites with generatepress.

What always bugs me is, why it there an html field in the customer for the copyright bar at the bottom when a widget could be used for that? Except this copyright field the customizer is nearly only responsible for design stuff and no content is defined in the customer. I would love the see a widget for the copyright bar in one of the next realeases.

Thank you very much
Andi

**Comment by tomusborne** [comment]
Thanks for the feedback!

You can use the "Footer Bar" widget area to add your copyright message if you'd like. You would need to disable the standard copyright message, though, which requires a filter (as of right now).

The Customizer option allows us to output the current year automatically as well, whereas a widget would require a shortcode to render it.

**Comment by mononox** [comment]
+1 for Copyright widgets

**Comment by tomusborne** [comment]
Looking at this, and I'm not sure there's a way to accomplish it in a backward-compatible way, unfortunately.

With the addition of Block Elements in GPP 1.11.0 and template tags coming soon, I would think that is likely the way of the future vs widgets.
