### ISSUE TITLE
Feature request - filter to change comment title from h3 to something else.

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generatepress#105]
Similar to this filter here but for comment title:
https://docs.generatepress.com/article/generate_start_widget_title/

**Comment by callaloo** [comment]
+1 for this.

**Comment by tomusborne** [comment]
`generate_comments_title_output` filter added in 3.0.0: https://github.com/tomusborne/generatepress/commit/b0e59bfa1e182fdf3f5e80b283210868fe76bb2a

**Comment by askel45** [comment]
@tomusborne thanks! Now if you could only add this to the documentation when 3.0 lands...
