### ISSUE TITLE
Typography REM support

### ISSUE THREAD

**Issue by AlexdeBorba** [tomusborne/generatepress#106]
Hello mates,

I have noticed that the Customiser only allows PX when it comes to Font Size under Typography and would like to suggest considering adding REM for better accessibility, as well as further compatibility with Elementor for instance, which offers this option on their typography other than limiting us to PX's.

I hope this can be considered for further releases, and it would be of great help.

**Comment by callaloo** [comment]
It should also include % if possible and a way to switch between them.

**Comment by swinggraphics** [comment]
@tomusborne Yes, it already looks like a field that you can change, and until I inspected the page and found it's just a span, I thought something was wrong.

**Comment by tomusborne** [comment]
We've added more units to our new Typography system in 3.1.0.

Thanks!
