### ISSUE TITLE
Feature Request - New Hook

### ISSUE THREAD

**Issue by askel45** [tomusborne/generatepress#107]
Something like `generate_before_archive_container` which appears between the page header and the main content in the archive pages.
1. https://prnt.sc/qcto22 
2. https://prnt.sc/qd6swb (where arrows are not crossed) cc @tomusborne

**Comment by tomusborne** [comment]
The page header on archives is hooked into the `generate_archive_title` hook: https://github.com/tomusborne/generatepress/blob/2.4.2/inc/structure/archives.php#L13

You should be able to use the same hook with a higher priority to place something under it.

**Comment by askel45** [comment]
Thanks. I did not know it was such simple. Let me test and see. I want to place breadcrumbs below the archive header on archive pages but after header on other areas.
