### ISSUE TITLE
Feature Request - Comment Icon for Reply Button

### ISSUE THREAD

**Issue by askel45** [tomusborne/generatepress#108]
Add a comment SVG icon before the Reply link in comments. Something similar to the one [used by Reddit.](http://prntscr.com/qsfuj9)

**Comment by tomusborne** [comment]
Definitely looks nice. Might be something worth considering if SVGs are enabled (I don't want to add more weight to the font icons).

For now, I think filtering the reply link output so we can easily add an icon if we want is a good call.

Thanks for the suggestion!

**Comment by callaloo** [comment]
You are welcome. I am using a Unicode icon for now using reply:before{content:"<icon here>"} and the [result is here](http://prntscr.com/qt1ycn). But SVG would look nicer.

**Comment by tomusborne** [comment]
This should actually be possible using a core filter: `comment_reply_link_args`

```
add_filter( 'comment_reply_link_args', function( $args ) {
    $args['before'] = 'Your SVG Icon HTML';

    return $args;
} );
```

**Comment by askel45** [comment]
I will test this in GP 3.0. Thanks

**Comment by tomusborne** [comment]
It's a core WP filter, so you don't have to wait for 3.0.
