### ISSUE TITLE
Polylang logo url not updating in sticky header

### ISSUE THREAD

**Issue by mononox** [tomusborne/generatepress#109]
Hi there,

I'm using Polylang to translate my website and I've just noticed the logo links back to the locale home url only when it's not in sticky mode? Is this a bug or perhaps not even intended?

You can see the behaviour here: https://mononox.com and https://mononox.com/de/ respectively.

Best Regards,
Sven

**Comment by tomusborne** [comment]
Hi there,

Are you doing anything special to make sure the regular logo links to the correct language? Both elements use the same code to link to the home page.

**Comment by mononox** [comment]
No changes, it's all out of the box. Perhaps the developer of Polylang has an idea what's happening here. I'll check back with them and report back with any updates.

**Comment by tomusborne** [comment]
Give this filter a shot:

    add_filter( 'generate_logo_href', function( $url ) {
        if ( function_exists( 'pll_home_url' ) ) {
            return pll_home_url();
        }

        return $url;
    } );

**Comment by mononox** [comment]
That works like a charm!

**Comment by tomusborne** [comment]
Glad I could help!
