### ISSUE TITLE
GP Premium: Metabox class HTML fix

### ISSUE THREAD

**Issue by Ruzgfpegk** [tomusborne/generatepress#110]
In the official gp-premium extension for this theme, version 1.9.1, in file elements\class-metabox.php, there is, starting on line 1016 and ending on line 1081:

```
			<table class="generate-elements-settings" data-tab="disable-elements" data-type="layout">
				<tbody>
[...]
				</body>
			</table>
````

The first closing tag should be ``</tbody>``.

It's a very small fix, but the file being outside the direct scope of this repository I can't just push a PR.

All credit is due to my IDE putting red warning lines all over its interface just because of that.

**Comment by tomusborne** [comment]
Thanks for this! Fixed in GPP 1.10.0. Appreciate the heads up.
