### ISSUE TITLE
Feature request: New hook to filter archive titles

### ISSUE THREAD

**Issue by askel45** [tomusborne/generatepress#113]
For accessibility purposes, it would make sense to introduce a filter to remove links from h2 archive titles similar to https://docs.generatepress.com/article/generate_featured_image_output/#example. (I use a read more button and some accessibility sites detect multiple links pointing to the same thing). cc @tomusborne

**Comment by askel45** [comment]
Thanks. I did the same for the image by adding the hook. I will be checking to see the new filter once you add it up coz right now I have edited the parent theme.

**Comment by tomusborne** [comment]
It's possible to use the `generate_show_title` filter on archives in GeneratePress 3.0.0. Hoping to get the alpha released next week.

Were you wanting to remove the titles completely, or just change the `h2`/remove the links?

Thanks!

**Comment by askel45** [comment]
@tomusborne I just want to remove the links on the h2 so only the "read more" button has a link. An alternative (which would force me to use a child theme) would be to retain the link on the heading but hide the excerpt and read more button from screen readers and keyboard users with `aria-hidden: true` (I am doing the latter on the underscores theme so screen readers cant see the image, excerpt and read more button on archive pages, only the title. But I think on GP, the first option would suffice.).

**Comment by tomusborne** [comment]
Just added this filter to 3.0 branch: https://github.com/tomusborne/generatepress/commit/9b3266e8d3bcc0e40a4544371d50fa9585929afc

Should do the trick 😄

**Comment by askel45** [comment]
@tomusborne thanks! Again, kindly do document this when 3.0 lands. Will test all these in the alpha release and report back.

**Comment by tomusborne** [comment]
Thank you!
