### ISSUE TITLE
Switch CSS to SASS (or SCSS)

### ISSUE THREAD

**Issue by BrookeDot** [tomusborne/generatepress#114]
This has come up in the forums a few times, but with version 3.0 now in Alpha, I figured it may be a good time to bring this up as an issue. 

Presumably, some process is currently being used to generate the `css/all.min.css` file behind the scenes. I'm wondering if now would be a good time to switch the `css` folder (or add a folder in addition) to a SASS folder which will allow better organization and customization. 

For now, it's simple enough to rename `style.css` to `style.scss` then have it build into `css/all.min.css`. I actually normally do this for my child theme and then dequeue the `all.min.css` from the main GeneratePress theme.

**Comment by tomusborne** [comment]
The `sass` folder in the 3.0.0 branch is worth checking out: https://github.com/tomusborne/generatepress/tree/release/3.0.0/sass

All of the stylesheets are now generated using `.scss` files by default. 

`all.min.css` is the "legacy" stylesheet with floats. 3.0.0 introduces a flex stylesheet by default which removes the need for unsemantic grid.

**Comment by BrookeDot** [comment]
:boom: I think we can close this since 3.0 looks like it solves this by using SCSS :partying_face:
