### ISSUE TITLE
Omit full-width-content from alignwide / alignfull

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#115]
Should we `:not(.full-width-content)` in alignwide/full selectors.

https://github.com/tomusborne/generatepress/blob/cd3de8b045136141358cbf273a6efbd9fad3732a/inc/css-output.php#L523

**Comment by tomusborne** [comment]
Yea that makes sense - is this causing x-scrollbars now?

**Comment by tomusborne** [comment]
Here we go: https://github.com/tomusborne/generatepress/commit/a7213652f2f01cec5dc671b57ef465d26c969df7

Opted to add more CSS vs adding more `:not` selectors.
