### ISSUE TITLE
CSS Optimization Breaks Site Styles

### ISSUE THREAD

**Issue by VR51** [tomusborne/generatepress#118]
There is an option to optimize CSS files that is found under Customizer > General. The options are 1) Combine CSS and 2) Cache Dynamic CSS.

Those two options when enabled can create two problems:

1. They stop CSS updates showing on the frontend immediately updates are applied.
2. Frontend styles break when other plugins also optimize CSS files.

Re conflict 1, clearing the browser cache does not cause CSS updates to show. The cache file has to be manually deleted from wp-content/cache/...

Re conflict 2, like conflict 1 above, the cached files have to be deleted manually when updates are applied because clicking a caching/optimization plugin's 'Delete Cache' button doesn't delete the cache created by GeneratePress; and, also, optimized CSS files seem to get processed twice because other cache plugins re-optimize them and so styles break.

FYI I tend to use the cache options provided by Optimize WP.

I like the optimization options provided by GeneratePress but I think there needs to be a 'Clear Theme Styles Cache' button (maybe labeled Clear GP Cache) added to the admin tool bar and a brief explainer near those options to say that when these options are enabled they can conflict with other optimization plugins.

Lee

**Comment by tomusborne** [comment]
Thanks for the feedback!

The Combine CSS option serves up the `all.min.css` file that's packaged with the theme. It doesn't do any caching and shouldn't cause any issues. It simply takes 3 files that are usually enqueued separately, and serves them in one file. This option no longer exists as of 3.0 if you're using the flexbox version of the theme.

The Cache Dynamic CSS file saves the CSS generated by your Customizer options in the database and serves them instead of having to generate on every page load. This option shouldn't need to regenerate ever unless something in the Customizer has changed or the theme is updated. It will automatically regenerate in those cases.

Can you outline some steps where I can reproduce the above issues? Happy to take a look.

**Comment by VR51** [comment]
It's a strange one. The issue shows up in a couple of sites but not all of them; possibly because I do not always enable the GP optimizations.

I will dig into one of the sites that had the issue persistently. This particular site used the Vinyasa theme from the Site Library. Prior to switching to GP about a month ago this site used Genesis + Dynamic Genesis (Cobalt Apps) -- my previous go-to combination.

So, in affected sites, as far as I recall, with Optimize WP enabled, with the cache in Optimize WP enabled and CSS optimization enabled in Optimize WP and the GP optimizations enabled through Customizer, any changes made sites configured this way required the static cache directory wp-content/cache/ to be deleted manually in order for any changes to show in the site's frontend. Often the site's custom CSS would not take effect after a CSS update in the Customizer.

Optimize WP has an option to enable browser resource caching. This option on or off, the issue was still present.

The Vinyasa site theme has a background image set at the top of the homepage. When changed this image just would not update until those GP optimizations were disabled.

Drove me crazy when I tried to pinpoint the cause of the issue because I'd forgotten about the GP optimization settings in Customizer. I spotted the settings by chance when adding new CSS styles. After toggling those GP optimization switches light-bulbs began to flick on and cogs began to whirr. I went through other affected sites to disable the GP optimizations. Disabling those GP options fixed the issue and it hasn't recurred since in those sites.

I will re-enable those GP options in this particular site and test again. Could be a few days before I get to do that.

I recently disabled WP Optimize in one of the affected sites and re-enabled GP optimizations. This other site is a multisite. The issue has not recurred in this site. I wonder whether the issue is confined to the combination of Optimize WP and the GP optimization settings.

**Comment by tomusborne** [comment]
I would be very surprised if it was the Combine CSS option - that should have relatively zero chance of causing issues like this.

The dynamic CSS cache could cause issues if it was failing to clear on save. Any caching plugin you use should automatically clear itself when it knows changes are being made (Customizer saved, pages/posts updated etc..). 

To test, I would activate the Combine CSS option only at first to rule it out. Then we can focus on the dynamic CSS cache option to see what's going on.

**Comment by VR51** [comment]
I'm in the middle of an urgent project that will consume most of my time today and tomorrow. I will run these tests as soon as I can do. Hopefully Friday. Thank you for bearing with me, Tom.

**Comment by VR51** [comment]
I apologise for the delay, Tom. I've not had much time to spend on this, however, the little ad hoc testing I've managed to do tells me the bug might be partially within Gutenberg. I've noticed that for some blocks the HTML updates properly but the Gutenberg meta surrounding the HTML sticks, especially URL references.

That being the case still doesn't answer the question of why wp-content/cache needs to be deleted before other edits show.

I wonder, could some of this be caused by the way sites are imported from either the library or JSON exports? Could a discrepancy in imported block meta prevent Gutenberg fully parsing/updating blocks when they are edited.

I'm clutching at straws. I know. Just wanted to let you know where my thoughts are at.

**Comment by tomusborne** [comment]
I can't see any reason why that would happen. It sounds like there's some weird caching going on with your server - is this something you can reproduce on a different server as well?

**Comment by askel45** [comment]
> The Cache Dynamic CSS file saves the CSS generated by your Customizer options in the database and serves them instead of having to generate on every page load.

I saw a comment by David that this option is not necessary if there is a cache plugin? @tomusborne

**Comment by VR51** [comment]
@tomusborne I look after many sites spread across different servers provided by the same host. I will eventually run tests in a local environment.

**Comment by tomusborne** [comment]
@askel45 it depends on the caching you have set up, but that's likely true - the caching plugin will cache it for you.

@VR51 Sounds good - interesting to hear if the same thing happens. Thanks!

**Comment by tomusborne** [comment]
Going to go ahead and close this for now. Let me know if any new information comes up 🙂
