### ISSUE TITLE
Entry-meta font size on mobile

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#123]
I have noticed the issue in two installations already. It’s minor but it’s there:

The `entry-meta` class on the single post has a `font-size: 85%;` property but it switches back to 100% on mobile (inherits the original size). As a result, the single post meta is slightly larger on mobile and it usually needs to be reset back to 85% or smaller.

```
@media (max-width: 768px) {
	.entry-meta {
		font-size: 85%;
	}
}
```

Is that by design?

GP versions prior to 2.1.3 didn’t have that issue. The issue was introduced on GB 2.1.3. Having elements go larger on a mobile view doesn’t seem natural.

**Comment by tomusborne** [comment]
Hi there,

Answered this here: https://generatepress.com/forums/topic/possible-bug-or-ommision-entry-meta-font-size-on-mobile/#post-1506661

The text shouldn't go larger than the surrounding text - it should just match the text around it.
