### ISSUE TITLE
Example Child Theme - Stylesheet File Import

### ISSUE THREAD

**Issue by clarknelson** [tomusborne/generatepress#125]
In inc/general.php:66, I had an error importing my child theme style.css. This is because there was a space in the path name. 

Maybe we can improve:

`wp_enqueue_style( 'generate-child', get_stylesheet_uri(), array( 'generate-style' ), filemtime( get_stylesheet_directory() . '/style.css' ), 'all' );`

To:

`wp_enqueue_style( 'generate-child', get_stylesheet_uri(), array( 'generate-style' ), filemtime( str_replace(' ', '\ ', get_stylesheet_directory()) . '/style.css' ), 'all' );`

**Comment by tomusborne** [comment]
I'm not sure having a space in the file name is a common enough thing to warrant a change in the core theme - especially as it involves running `str_replace()` when it wouldn't be necessary for most people.

If you need a space in your file name, you're likely better off disabling the core child theme enqueue and adding your own: 

`add_filter( 'generate_load_child_theme_stylesheet', '__return_false' );`

**Comment by clarknelson** [comment]
Thanks Tom, love the theme
