### ISSUE TITLE
Child Theme inc/structure Imports

### ISSUE THREAD

**Issue by clarknelson** [tomusborne/generatepress#127]
In functions.php:73

`$theme_dir = get_template_directory();`

will not recognize the child directory, maybe should be:

`$theme_dir = get_stylesheet_directory();`

**Comment by clarknelson** [comment]
Ah I see that each structure would need to be copied, is there a good way to overwrite these files in a child theme?

**Comment by tomusborne** [comment]
It's typically not a good idea to overwrite any of those files in a child theme. Most things in the theme have filters you should take advantage of instead of overwriting entire sets of functions.
