### ISSUE TITLE
Add Required Attrbute to Comment Form

### ISSUE THREAD

**Issue by BrookeDot** [tomusborne/generatepress#130]
GeneratePress adds the `generate_set_comment_form_defaults` function to the `comment_form_default_fields` filter. 
https://github.com/tomusborne/generatepress/blob/e030f57d2c26991074a6868265737424dac567d0/inc/structure/comments.php#L142-L175

As part of the filtering process, the `required=required` attribute is removed when HTML5 is enabled and "Comment author must fill out name and email" is checked in the site's Discussion settings. You can see WordPress core adds this here:
https://github.com/WordPress/WordPress/blob/5.5-branch/wp-includes/comment-template.php#L2329

Due to some accessibility and localization issues with HTML5 form validation, the `novalidate` attribute is added. However, this is occasionally discussed at the core level most recently in https://core.trac.wordpress.org/ticket/47595. 

When I build sites I use a bit of JavaScript to remove the `novalidate` and was banging my head against the wall to figure out why that worked in other themes but not in GeneratePress and dug in which brought me to file this issue.

My solution was to use `remove_action( 'generate_set_comment_form_defaults', 'comment_form_default_fields' );` in my `after_theme_setup` of my child theme. While removing the filter and falling back on WordPress' `comment_form()` function works as expected, I would suggest checking for the Discussion setting to be checked then adding `required=required` to the fields if so. 

That way HTML5 validation can be used if WordPress core implements a filter to remove `novalidate` or does so at the core level in the future.

**Comment by BrookeDot** [comment]
@tomusborne if I create a PR for this are you interested in implementing it in a future release?

**Comment by tomusborne** [comment]
Sorry for not responding here! I've added this to 3.1: https://github.com/tomusborne/generatepress/commit/d405c1444b36d234c50c146fff5a306d65681968

Thanks!
