### ISSUE TITLE
Typography re-write

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#131]
Beginning in 3.1, I'd like to do a full typography re-write.

* Needs to be in-sync with a GPP update with the same functionality
* Ability to add custom font name values in the Customizer
* Conditional loading of the G Fonts list in the select dropdowns

Pre-loading etc..: https://generatepress.com/forums/topic/the-fastest-google-fonts-functions-php

**Comment by SchneiderSam** [comment]
@tomusborne 

I am testing 3.1.0-alpha. Really nice features. The typo and the global color is really cool!! Can't wait ;-)

**Comment by tomusborne** [comment]
Close to completing this for 3.1. Going to close this now as we'll open up other more specific issues for anything remaining.
