### ISSUE TITLE
Add hooks for search

### ISSUE THREAD

**Issue by BrookeDot** [tomusborne/generatepress#132]
Many templates have a set of standard hooks that can be used to modify content. For example, the `archive` template hooks are found in `inc/structure/archives.php`. These are missing for the search results page and title. I'd expect to be able to filer after the search title the same way I do with archive. Ie `generate_after_search_title` in place of `generate_after_archive_title`.

**Comment by BrookeDot** [comment]
Looking at this more I think the best option for the moment is to overwrite `search.php` in my child theme. I still think having this feature in the future would be beneficial, but may result in breaking changes for some theme users or would require some messy backwards compatibility code.

I'd be happy to try a PR adding `inc/structure/search.php` and modifying `search.php` but not sure how to do that in a way that won't break backwards compatibility :)

**Comment by tomusborne** [comment]
Added in 3.1. Thanks!
