### ISSUE TITLE
Sticky navigation loads logo over http instead of https

### ISSUE THREAD

**Issue by billyjacoby** [tomusborne/generatepress#135]
This is one that has been driving me crazy for a while now.

For some reason the stick navigation loads the logo file over http instead of https. I tried finding exactly where this happens in the theme, but I'm not terribly familiar with development on Wordpress themes.

If you could point me in the right direction I'd be happy to make a pull request to fix this issue. Thanks!

**Comment by leohsiang** [comment]
Hi there,

Can you open a topic in our support forum first?
https://generatepress.com/support/

Thanks :)

**Comment by billyjacoby** [comment]
I tried doing that, I don't have an account though and I'm not sure where to get one? I'm doing this work on one of my client websites.

**Comment by leohsiang** [comment]
That's a premium forum so it requires a valid license to access.

You will need to get the login info from your client.

Thank you.

**Comment by billyjacoby** [comment]
I'll see if I can get that from the client.

In the meantime I edited the source code on the website and was able to locate the issue.

Line number 2072 of the `/menu-plus/functions/generate-menu-plus.php` was where I found the issue and fixed it.

Let me know if you'd like more info. Thanks!

**Comment by tomusborne** [comment]
Line 2072 of that file is a PHP doc - not any code? What version are you using?

All URLs are taken from your options in the Customizer, which will use the URL you have set in Settings > General.

**Comment by billyjacoby** [comment]
Sorry, it looks like I was referring to the premium plugin. 

Version number is 1.12.3

The `generate_do_navigation_branding()` function was where my issue was. Line 2077 of the file is what was pertinent to me as I was trying to fix the sticky logo https issue.

The exact file location is:
`gp-premium/menu-plus/functions/generate-menu-plus.php`

If you'd like more info on what I did to fix it I'd love to help, just don't wanna share your code in an open forum since it is a premium plugin that the client is using.
