### ISSUE TITLE
Issue with generate_set_customer_helpers()

### ISSUE THREAD

**Issue by WvHDev** [tomusborne/generatepress#138]
Hello

For some reason my website keeps showing a fatal error

[Mon Jan 25 15:15:39.196812 2021] [php7:error] [pid 1054] PHP Fatal error:  Cannot redeclare generate_set_customizer_helpers() (previously declared in /home/public/sites/www.examplenl/wp-content/themes/generatepress/inc/customizer.php:20) in /home/public/sites/www.example.nl/wp-content/themes/generatepress/inc/customizer.php on line 20, referer: https://example/oefeningen/toevoegen/?a=2

add_action( 'customize_register', 'generate_set_customizer_helpers', 1 );
/**
 * Set up helpers early so they're always available.
 * Other modules might need access to them at some point.
 *
 * @since 2.0
 */
function generate_set_customizer_helpers() {
	require_once trailingslashit( get_template_directory() ) . 'inc/customizer/customizer-helpers.php';
}

I've also added the question to stockoverflow, but I'm not getting any further. Is this a bug from generatepress?
If so, how can I resolve this?

**Comment by tomusborne** [comment]
This error means that you're trying to define that function name even though it already exists.

Are you adding any custom functions to your site? Anything in the child theme?

**Comment by WvHDev** [comment]
I understand! I do have other files in the theme and custom functions, but I don't use the above function. Except for the files from Generatepress, but I did not alter them.

Is there a conflict or something?

The page where I get this error from is doing a $.POST {} request.. maybe this can be an issue?

**Comment by tomusborne** [comment]
Hard for me to know, unfortunately. It means something in your code is loading that file even though it's already been loaded. Something using `require` for that file in your code, perhaps?
