### ISSUE TITLE
Consider using SemVer to versioning GeneratePress and GP Premium

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#14]
## Usage
The version number will use three numbers: MAJOR.MINOR.PATCH (Similar to your current approach).

### MAJOR
Changes when a release breaks (not compatible with) the previous release.

### MINOR
Changes when a release brings a new functionality BUT NOT breaks the previous release.

### PATCH
Changes when a release brings a just bug fixes.

---

Reference: http://semver.org/

**Comment by tomusborne** [comment]
Ha, you read my mind! Next updates will be using this :)

**Comment by luizbills** [comment]
WTF so fast hahahah

Thank you, Tom. It will be a great achievement.
