### ISSUE TITLE
Too many footer widgets shown

### ISSUE THREAD

**Issue by NicoHood** [tomusborne/generatepress#148]
I am using Generatepress 3.0.3 **without** the premium plugin. When I go the homepage>customize>widgets there are 5 footer widgets shown, even though only 3 (default) are configured in the layout settings:

![grafik](https://user-images.githubusercontent.com/6888294/111365049-4bcceb00-8692-11eb-9c1a-82ffb38856ca.png)

![grafik](https://user-images.githubusercontent.com/6888294/111365085-57201680-8692-11eb-9844-c75f4f5b50e3.png)

When you try to add something to widget 4 or 5, the content is not shown. If you add something to 1-3, then widget menu 4-5 disappear. This should be very easy to reproduce on a clean website.

**Comment by leohsiang** [comment]
Thanks! I was able to replicate this.

Will improve it :)

**Comment by tomusborne** [comment]
I've looked at this before, but it's necessary to show all available widget areas as users can change the number of widget areas to display on a per-page basis.

**Comment by NicoHood** [comment]
If that is true, the number of widgets should never decrease if the layout designer chooses less widgets. Also it should not behave that buggy, that 4 & 5 only disappear when 1-3 are set. They should never disappear, right?

**Comment by tomusborne** [comment]
Do you mean in the Customizer? WordPress itself hides/shows widget areas based on their available per page, so maybe that's what you're seeing?

**Comment by NicoHood** [comment]
Yeah, an it is glitching. Just try it out. Leo confirmed this.
