### ISSUE TITLE
Add schema markup to comments

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#15]
Add appropriate schema.org markup to comments.

**Comment by luizbills** [comment]
a good start point: https://stackoverflow.com/questions/8858844/how-to-use-the-usercomments-schema-item

**Comment by inetbiz** [comment]
And, modifying content.php that calls comments with a wrapped `<section>` tag. And creating nested articles within the article. See http://html5doctor.com/the-article-element/ The article with nested comment section.

**Comment by inetbiz** [comment]
I noticed this is a nine month old issue. I hope it's added to your active list very soon?

**Comment by tomusborne** [comment]
Absolutely - we wanted to focus on getting 2.0 out first.

Thanks!

**Comment by tomusborne** [comment]
First pass at this here: https://github.com/tomusborne/generatepress/commit/9781c14663b2355d628f6cf1597e9a4179065dc4
