### ISSUE TITLE
Selected Navigation Item Text default color bad contrast

### ISSUE THREAD

**Issue by NicoHood** [tomusborne/generatepress#151]
The default Navigation bar looks like this:
![grafik](https://user-images.githubusercontent.com/6888294/111387487-146c3780-86ae-11eb-969a-0d03bf71d37c.png)

It uses `#7a8896` for the currently selected item and `#515151` for all others. The first color does not pass the AA contrast check and should be changed. You will have problems reading that text on bright environments, beamers, and on my laptop screen.
https://webaim.org/resources/contrastchecker/

This color cannot be changed within the free version, however even in premium a new default should be picked. Same for hover effect.

**Comment by tomusborne** [comment]
We've adjusted this in the 3.1.0 update. Thank you!
