### ISSUE TITLE
Comment Form: Attribute aria-required is unnecessary for elements that have attribute required.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#155]
W3 validator flags this:

Warning: Attribute aria-required is unnecessary for elements that have attribute required.

https://github.com/tomusborne/generatepress/blob/7b35168f546f83a7abb098a8da3bc0674d49ddeb/inc/structure/comments.php#L128

**Comment by tomusborne** [comment]
Fixed in 3.1: https://github.com/tomusborne/generatepress/commit/9747de4be7497efed8d6698e231957790a97eda7
