### ISSUE TITLE
Feature request: "Integrated Color Palette" for GeneratePress and GenerateBlocks

### ISSUE THREAD

**Issue by ejcabquina** [tomusborne/generatepress#156]
A request for a single color palette that can be used with GenerateBlocks and GeneratePress.

Context: https://generatepress.com/forums/topic/wanted-integrated-color-palette/

**Comment by rockyviewweb** [comment]
Yes, please! :)

**Comment by SchneiderSam** [comment]
Me too pls!

**Comment by hashimnaushahi** [comment]
+1

**Comment by muchadesign** [comment]
+1

**Comment by Jehu** [comment]
+1

**Comment by tomusborne** [comment]
GP 3.1.0 has a global color palette that integrates with the editor and can be used in GenerateBlocks 1.4.0.

Both updates coming in August.
