### ISSUE TITLE
FSE, Global Styles and Global Settings and GP 3.1

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#162]
Looking at the development, you guys are working on the Customizer right now.: https://github.com/tomusborne/generatepress/commits/feature/customizer-rebuild

Nice!

Wordpress is working at full speed on FSE. Among other things also on Global Setting and Global Styles: https://riad.blog/2021/05/05/introduction-to-wordpresss-global-styles-and-global-settings/

Since, this is no longer to be considered experimental, but forward-looking, I wonder how GP deals with it? Does that work hand in hand or will GP and GB work completely different?

**Comment by tomusborne** [comment]
Been following this quite closely as well. From what I can gather, the system they're putting in place is great for static themes - think a Twenty-something theme. You can define the theme styles/settings in the `theme.json` file and the editor will respect your choices.

However, GeneratePress isn't a static/Twenty-something theme - everything is dynamic. Everything from typography to colors is defined by the user, not us (the theme developers). So, unless that .json file was generated and updated dynamically to include the preferences you've chosen in the Customizer (not sure there's much point to that), I don't think it will apply to a theme like GP.

Of course, this can change, and I'm willing to hear other opinions/thoughts on it.
