### ISSUE TITLE
comments_open condition on loading comments.min.css does not apply to Closed Comments

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#163]
Condition isn't met and no styles loaded if Comments have been closed.

https://github.com/tomusborne/generatepress/blob/b60b853630da6d9015722da903e53c8064148b0a/inc/general.php#L22

**Comment by tomusborne** [comment]
Fixed in 3.1 https://github.com/tomusborne/generatepress/pull/171
