### ISSUE TITLE
capacity to disable support to old IE versions

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#17]
WP 4.8 (next major release) will end support for IE 8, 9, 10. An option to disable the support to old IE will be nice in the GeneratePress too. Maybe a option in `Apparence > GeneratePress` or just a `filter`.

**Comment by tomusborne** [comment]
You can currently do this with a function:

    add_action( 'wp_enqueue_scripts', 'tu_remove_ie8'. 20 );
    function tu_remove_ie8() {
        wp_dequeue_script( 'generate-html5' );
	wp_dequeue_style( 'generate-ie' );
    }

I'm thinking about removing it from core altogether, however WP simply stated that future updates won't be < IE11 compatible, so old features will still be compatible.

**Comment by luizbills** [comment]
+1 for removing it from core. But I think that an some users still need support for old IE, so a filter or a tutorial will be very helpful.

**Comment by tomusborne** [comment]
I think a scripts section in the Customizer might be best.

- Disable old IE scripts
- Remove FontAwesome/include only the essentials

Need to think of some others to add in there.

**Comment by luizbills** [comment]
Something like a painel "Otimizations" in the customizer? Nice!
