### ISSUE TITLE
remove the unsemantic grid

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#21]
The unsemantic grid is almost unnecessary in the theme (making it easy to replace it) and removing it will make the theme more lightweight and less opinionated. I believe that many users should not even take advantage of this grid framework, but you should know it better than I do.

**Comment by tomusborne** [comment]
Unfortunately there's likely too many people out there relying on the grid in order to remove it.

An option to only include essentials classes the theme uses (much like the Font Awesome filter) could definitely happen though :)

**Comment by luizbills** [comment]
Good idea

**Comment by luizbills** [comment]
I'll send a PR. Can you tell me where in the theme the unsemantic is used? 
*At the moment I only remember the columns in the footer.*

**Comment by tomusborne** [comment]
The sidebar/content area system mainly. 

`.grid-container` is used in a lot of places.

Footer area as you said.

Thanks!

**Comment by luizbills** [comment]
I think it will not be worth creating an *essentials* version of the grid because of the width possibilities of the sidebar. Almost all `.grid-*` are used in the sidebars and content area.

**Comment by tomusborne** [comment]
Yea, only a few of the smaller percentages aren't used. I'll look into it some more and see if I can come up with something :)
