### ISSUE TITLE
.entry-content margin when title is disabled

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#22]
Currently the margin is removed on pages, but sometimes it needs to be removed elsewhere (Elementor library items).

Perhaps it would be better to apply the margin to the title itself instead of the content.

**Comment by luizbills** [comment]
is there any body class when the title is disabled?

**Comment by tomusborne** [comment]
There isn't, we just check to see if it's disabled here: https://github.com/tomusborne/generatepress/blob/master/functions.php#L501

However right now it's set to `.page` only.

**Comment by luizbills** [comment]
Apply the margin to the title itself will be the easiest solution even.

**Comment by tomusborne** [comment]
Problem with that is the entry meta on single posts.

**Comment by tomusborne** [comment]
https://github.com/tomusborne/generatepress/commit/20b0239e0146e2ed92aefe9754592f54761ba549
