### ISSUE TITLE
Typography dropdown inaccessible when close to end of screen

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#234]
### Description
When the typography dropdown is too close to the edge of the viewport, it becomes inaccesible.

### Steps to reproduce
1. Add enough items to get a dropdown close to the end of the Customizer: https://www.screencast.com/t/3SsOjSIT

#### Expected behavior
It should pop up instead of down when that close to the edge.

#### Actual behavior
It opens down even though there is very little space.

**Comment by tomusborne** [comment]
I wonder if the Popover component is the right choice for the Customizer? We could just have the options dropdown instead.

**Comment by JeanPaiva** [comment]
@tomusborne what about opening the third panel? Similar when choosing menu items

**Comment by tomusborne** [comment]
@JeanPaiva that would be cool but I'm not sure if the Customizer has an available method for us to utilize.

**Comment by JeanPaiva** [comment]
Fixed by #235
