### ISSUE TITLE
No icon/label on search submit button on search result page when using Flexbox + Font

### ISSUE THREAD

**Issue by leohsiang** [tomusborne/generatepress#240]
### Description

No icon/label on search submit button on search result page when using Flexbox + Font

Floats + Font: https://www.screencast.com/t/MHb8vXIDCvy
Flex + Font: https://www.screencast.com/t/oTF4Gdt7ElPb

### Steps to reproduce
1. 

#### Expected behavior
...

#### Actual behavior
...

#### References: 
...

-----

**Comment by JeanPaiva** [comment]
It's a confirmed bug. Also, you can't have `Floats/SVG` combination, it will always display the search text.

**Comment by tomusborne** [comment]
Yea, this was fixed here I believe: https://github.com/tomusborne/generatepress/pull/192
