### ISSUE TITLE
Suggestion: separate Gutenberg palette colors

### ISSUE THREAD

**Issue by ghost** [tomusborne/generatepress#241]
### Description
Hello. I am testing GeneratePress 3.1. I would like to have the possibility of defining which one of the global colors must be available for use inside the block editor.
GeneratePress 3.1 itself defined 7 default global colors: 3 contrasts, 3 bases and 1 accent. I can change their values and add more if necessary. However, all global colors are going to appear inside the block editor. And not necessarily I want all those global colors to be available when editing a post, because I define many global colors in similar shades of gray and blues which are useful for me adjusting the theme categories (Base, Header, Primary nav, Buttons, Content, ...). However, when editing a post, I prefer the old way, using Gutenberg's strong reds, yellows, greens predefined. I understand I can add those strong colors as my Global Colors, but I would still not enjoy the solution in which I am going to be able to see all global colors and gutenberg colors together when editing a post.
The solution I suggest is to create a new category named (in lack of a better name) "Colors for the Edit page" in which I am going to adjust what are the theme colors specifically available for use inside the block editor palette.

![image](https://user-images.githubusercontent.com/85775951/128249880-e0817d9e-e498-4160-b46a-90409001cab7.png)

**Comment by JeanPaiva** [comment]
Related to #307 and #310
