### ISSUE TITLE
Bug: unable to save new global colors

### ISSUE THREAD

**Issue by kindnesstotheworld** [tomusborne/generatepress#242]
### Description
Hello. I am testing GeneratePress 3.1.
I was able to add and name new Global Colors, but I was unable to save them. When I refresh the Customizer, my recently added global colors are gone.

Only saving changes on one of the 7 default global colors was I able to do.

### Steps to reproduce
1. Customizer -> Colors section -> add a new Global Color and name it or not.
2. Click on Publish to save the addition and Refresh the page.
3. No changes were recorded.

**Comment by JeanPaiva** [comment]
It's a confirmed bug. Thank you @kindnesstotheworld

**Comment by JeanPaiva** [comment]
@kindnesstotheworld it's fixed in the `release/3.1.0` branch, thank you again!
