### ISSUE TITLE
Always allow Google Font toggle

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#270]
Right now the Google Font toggle in the font manager disables itself if the font you enter doesn't exist in the list of Google fonts we generate.

However, it seems like that list isn't 100% complete (https://generatepress.com/forums/topic/google-font-droid-arabic-kufi/#post-1931930), which means users can't tell the system to use the Google API if the value they enter isn't in our list.

We should allow users to always toggle this option regardless of font name to avoid issues like this.

**Comment by Mahmoud-AbdEllFttah** [comment]
Users must already be allowed to choose the right font for them from Google Font.
With interest, of course, in the following:
- The speed at which the Google  Font appears on the site.
This is important and vital.
**Especially in the Middle East who rely on the use of Arabic.**

Thank you dear Tom for opening this case here.

**Comment by JeanPaiva** [comment]
#271 will fix this issue.

**Comment by JeanPaiva** [comment]
Fixed by #271
