### ISSUE TITLE
Use get_the_archive_description()

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#275]
### Description
Right now we use `term_description()` and `get_the_author_meta( 'description' )` separately so we can add different classes to their containers: https://github.com/tomusborne/generatepress/blob/3.0.4/inc/structure/archives.php#L100

It would be better to use `get_the_archive_description()` so users can take advantage of the core filter to alter the output. We just need to make sure we can implement our current HTML classes so we don't break any existing user customizations.

#### References: 
https://generatepress.com/forums/topic/modify-archive-description/#post-1932447

**Comment by JeanPaiva** [comment]
@tomusborne you want to add this to 3.1.0? I can work on this, just let me know.
