### ISSUE TITLE
Option to lazyload google fonts

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#28]
Will improve performance and prevent site text from blinking.

Requires [Web Font Loader](https://github.com/typekit/webfontloader).

**Comment by tomusborne** [comment]
Yea, I like this. I have plans to re-write most of the typography functions once the latest updates are out and stable :)

**Comment by trsenna** [comment]
Hi,

within the Autoptimize plugin you can check the following option - _Combine and load fonts asynchronously with webfont.js_ under the Extra tab. It's a nice feature, but maybe better to keep as plugin territory.

**Comment by tomusborne** [comment]
I think this may be better left to plugins, as they handle all Google font requests (if you're loading them from more than just the theme).
