### ISSUE TITLE
Table Styling

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#301]
Aside from the core Table Block styles not displaying correctly on the front end. There have been several user requests for Customizer functionality to set Table Styles.

This 'feature request' is more a  'let's open some dialog' about possible options that  could be added to the Theme in the future.

**Comment by SchneiderSam** [comment]
Isn't that more of a block? I'm not sure that's soo important for GP. There are much more important areas, aren't there?! There are so many good plugins for tables out there: https://wordpress.org/plugins/search/table/

**Comment by diggeddy** [comment]
Closed. Consider CSS if requried.
