### ISSUE TITLE
Always show Top Bar colors

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#308]
Right now we hide the Top Bar color fields if nothing is added to the top bar (https://github.com/tomusborne/generatepress/blob/3.1.0/inc/customizer/fields/top-bar.php#L20). It would be better to always show the fields so users can set up their colors for future use, even if the widget area isn't in use yet.

**Comment by JeanPaiva** [comment]
We fixed this on #314 on `release/3.2.0 branch`.
