### ISSUE TITLE
GP Hooks

### ISSUE THREAD

**Issue by mmjaeger** [tomusborne/generatepress#31]
Hello
what I was wondering whether it would be helpful to have a meta box for the hooks on the pages as well so it would apply only to the current page - that way we could have some global hook content as well as per page - the only other way to achieve this is having to put some PHP conditions into the hooks - maybe I'm missing something?

**Comment by mmjaeger** [comment]
Anybody watching github? How about adding priority as well

**Comment by luizbills** [comment]
@tomusborne

**Comment by tomusborne** [comment]
A priority option is in the works.

As for a meta box, I would need to see an example or a mockup - something like that could be super powerful, but it would need to be done right.

**Comment by mmjaeger** [comment]
Maybe bloxwp could give you some ideas?
