### ISSUE TITLE
Customizer global colors UI improvements

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#310]
Regarding the UI improvement for global colors: I run into an issue where I had named a color as one of the base color variants (eg, base-2) and realized it was actually an accent color. Of course, I had used it throughout the site. In this case, it would be a pain to rename it to an accent color variant as I would need to go and replace all the color values throughout the site. I was thinking of a REPLACE function where a Customizer color name change would also replace all instances of that color throughout the site. In combination with a drag and drop function to rearrange global colors in the Customizer, this would prove a life saver.

**Comment by JeanPaiva** [comment]
@quantumleap33 thank you for your feature request. We certainly have a couple of improvements necessary for global colors, for the release, we focused mainly on making the core functionality stable and backward compatible.

Our next step is to improve UX/UI for global colors and other improvements to facilitate the usage.

Again, thank you for your feedback.

Related to #307

**Comment by tomusborne** [comment]
This is a tricky one as it's typically not a good idea to change the names once you've started, especially if you've been using the variables in your content (GB blocks).

Going to push this to 3.3.0 so we have more time to think on it.

**Comment by diggeddy** [comment]
This would require extensive search and replacing of color variables and `has-` utlitly classes in  the theme and in the content. And there is no practical or stable way to do this.
Closing as no fix.
