### ISSUE TITLE
Global Color - CSS Variable Name won't accept Caps Lock text

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#316]
The CSS Variable name field doesn't accept text (alpha only) if Caps Lock is enabled.
Not an issue if we want to limit the CSS Variable to lower-kebab-case, but its currently a bad UI as typing into the field doesn't work

**Comment by JeanPaiva** [comment]
@diggeddy and @tomusborne to improve UI a bit, we can check for upper case chars and display a message for user that is not allowed and it will be saved as a lower case to keep consistency.

**Comment by JeanPaiva** [comment]
@diggeddy what do you think about this help text once you type wrong characters on the variable name?

![Image](https://user-images.githubusercontent.com/7506830/169914250-b2c45b16-437a-48bc-aab3-4f305986e7cb.png)
