### ISSUE TITLE
Post estimated reading time functionality

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#332]
This is just a feature request for adding a post estimated reading time functionality. Possibly, this code could be adjusted to make it work in GP:
https://medium.com/@shaikh.nadeem/how-to-add-reading-time-in-wordpress-without-using-plugin-d2e8af7b1239

**Comment by diggeddy** [comment]
Closed.
This is effectively post meta, and the theme should not be writing that for any reasons other then its own.
And these functions are not consistent for different language types.
