### ISSUE TITLE
generate_woocommerce_start is used in archive templates too, leads to double article container

### ISSUE THREAD

**Issue by frafor1988** [tomusborne/generatepress#344]
### Description
I noticed that my WooCommerce archives were wrapper in `<article></article>` tags reporting the IDs/Classes of the 1st product in the loop. After some digging, I noticed that the generate_woocommerce_start function, used to inject GP's content div and main wrapper, adds the `<article></article>` tag too as it's maybe supposed to work in single product template.

### Steps to reproduce
1. Set up a woocommerce store
2. Check the HTML in product archives

#### Expected behavior
Products should be enclosed in the archive container

#### Actual behavior
instead they're enclosed in `<article></article>` tag with IDs/Classes coming from the 1st product in the loop

**Comment by JeanPaiva** [comment]
@frafor1988 thank you for pointing out this bug. I added to the backlog of our next big release.

**Comment by frafor1988** [comment]
@JeanPaiva damn you're fast! thank you for the great work here ;)

**Comment by frafor1988** [comment]
Also, the 1st product content is used as description text in the .page-description div (just below the archive title)

**Comment by ptrsmk** [comment]
Wouldn't this be solved by merely adding
`if( ! is_product() ) return;`
to the start of `generate_woocommerce_start()`?

**Comment by tomusborne** [comment]
Hey @frafor1988 - thanks for the bug report!

I've just opened a PR with a fix if you want to give it a try: https://github.com/tomusborne/generatepress/pull/369

Thanks!
