### ISSUE TITLE
Custom local font not loaded in Editor since 3.1.3

### ISSUE THREAD

**Issue by quimic** [tomusborne/generatepress#350]
### Description
In version 3.1.3 (Wordpress 5.9), despite @font-face rules and font-family rules in an editor stylesheet, local font files are not displayed in the editor.
Browsers dev tools show that no font files queries are made.

### Steps to reproduce
1. Add an editor stylesheet with @font-face rule pointing to local font file and appropriate font-family rules
2. Edit a post or page

#### Expected behavior
The editor displays the specified font

#### Actual behavior
The editor displays the default system font

-----

**Comment by tomusborne** [comment]
How are you adding your custom editor stylesheet currently?

**Comment by quimic** [comment]
Hi Tom,
I am using the add_editor_style function in the functions.php file.
Styles are properly applied, but the fonts are not loaded. Not a huge deal, but this was working yesterday, so I think it might have something to do with the latest update.

Michel

**Comment by tomusborne** [comment]
We had to switch to use `add_editor_style()` in 3.1.3 so our editor styles would work in WP 5.9.

Try adding your styles like this now:

```
add_filter( 'generate_editor_styles', function( $editor_styles ) {
    $editor_styles[] = 'relative/path/to/your/style.css';

    return $editor_styles;
} );
```

**Comment by quimic** [comment]
The behaviour is identical: the stylesheet gets loaded and the styles are applied, but the fonts are not loaded (no queries are made).

**Comment by quimic** [comment]
If that helps, I see this in Firefox dev tools:



The used rule show my font family (Alegreya, etc.), yet the resulting font family is the system one.

**Comment by tomusborne** [comment]
Hard to tell what's happening by that screenshot.

Can you share the contents of your editor stylesheet?

**Comment by quimic** [comment]
Sure. Here it is. It is a bit big as it is a taken from my front-end stylesheet.
[editor-style.css.zip](https://github.com/tomusborne/generatepress/files/8043758/editor-style.css.zip)

I doubt the issue is related to the styles though, since it was working on 3.1.2

**Comment by tomusborne** [comment]
The issue is likely due to us adding this theme support: https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles

What it does is prepend your editor CSS selectors with `.editor-styles-wrapper`, and replace `body` with it as well.

For example:

```
body {
    font-size: 17px;
}
```

Will be converted to:

```
.editor-styles-wrapper {
    font-size: 17px;
}
```

And:

```
h1 {
    font-size: 30px;
}
```

Will be converted to:

```
.editor-styles-wrapper h1 {
    font-size: 30px;
}
```

With that in mind, you may need to update your CSS file so all your CSS remains valid after WordPress makes these changes.

**Comment by quimic** [comment]
I see this automatic conversion in dev tools, and I can see that it is working well. All the styles are properly applied. The only issue is that the font family rule is no longer applied. As shown in the dev tools screenshot, the browser sees the font-family rule for .editor-styles-wrapper, but for some reason, the font is not loaded.

**Comment by tomusborne** [comment]
I think the issue here is that the font URLs are relative in your CSS. WP takes your CSS from the file (where the relativity works) and loads it inline in the editor, where that relativity breaks.

Try adding the absolutely URL to the font URLs and it should work.
