### ISSUE TITLE
Code block is appearing extra wide since few weeks

### ISSUE THREAD

**Issue by tech-vin** [tomusborne/generatepress#355]
### Description
Code block is appearing wide in editing mode since last week.

### Steps to reproduce
1. updated theme : not solved
2.  tried custom css : not solved

#### Expected behavior
the width of the code block must be same as other content on the website.
Content look fine when published or previewed

#### Actual behavior
Width of code block starts from the start of the window and stretched till the end.

#### References: 
below image shows the increased size of code block in the editing mode.
![image](https://user-images.githubusercontent.com/54138655/154931157-aae2a078-afc0-45f7-a395-ec1c2b8bd5a0.png)

-----

**Comment by JeanPaiva** [comment]
Hey @tech-vin can you give a try on this PR: https://github.com/tomusborne/generatepress/pull/349
