### ISSUE TITLE
GP Premium requirements when GeneratePress theme is install but not activated

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#356]
When GeneratePress is installed but not activated along with an activated GP Premium plugin, there is a notice at the top saying:

> GP Premium requires GeneratePress to be your active theme. Install now.

It should only say that when GeneratePress is not installed. When it is installed, it should say:

> GP Premium requires GeneratePress to be your active theme. Activate now.

**Comment by vvaz** [comment]
This also happens when you use a child theme of GeneratePress. Didn't see any break in functionality.

**Comment by diggeddy** [comment]
Not seeing issue on Child Theme, as long as the correct template name is set.
Adding extra condition to determine whether the theme is installed but inactive to change one word is not worth it, especially as the Install Now link handles the Activate option for you

wont fix. Closing.
