### ISSUE TITLE
horizontal scrollbar

### ISSUE THREAD

**Issue by mmjaeger** [tomusborne/generatepress#36]
Hello
I'm getting a horizontal scrollbar using the builder template - when adding a overflow: hidden to .container.grid-container the issue goes away?

**Comment by tomusborne** [comment]
Which builder template? Adding overflow:hidden would definitely stop horizontal scroll, but it's kind of a blanket to the original problem. If anything, the section within your content which causes horizontal scroll should have hidden overflow, not the entire container.
