### ISSUE TITLE
Global colors not working with core image duotone filter

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#362]
Seems like the core image duotone filter cannot accept GP global colors as custom color values. Only custom values seem to be accepted.
https://www.loom.com/share/0812399790104ba083c0dbf8f46835f8

**Comment by diggeddy** [comment]
This cannot be fixed by the theme.
The duotone is created by core using a `fecolormatrix` in a SVG `fillter` and it has  no support for CSS Variables.

Closing.
