### ISSUE TITLE
Ability to cascade Customizer variable name change throughout the site

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#384]
GP 3.2.0 adds color reordering to the Customizer global colors which is great. I would like to propose another useful feature and that is the ability to be able to rename the Customizer global color variables but for all the existing colors in the block editor to be able to be replaced with that new name. Right now, when you rename a global color variable from the Customizer, you get a notification popup saying `Changing this name will break styles that are using it to define its color.` It would be great if already defined colors would be able to inherit the change.

Imagine the following scenario. A user constructs the palette of colors in the Customizer. As the colors are added the user rearranges the colors as new useful colors are being added. At this stage, naming wouldn't make sense since the colors are quickly added and being dragged around. If a sequential naming convention is used (contrast, contrast-1, constrast-2), colors would end up in the wrong order. With what I propose, users could rename their global colors at the end of the color palette construction with naming that makes sense and they would have already assigned colors taking up the new naming.

**Comment by JeanPaiva** [comment]
@quantumleap33 is related to #310 . Its on the radar, but I don't think we will release it on 3.2

**Comment by quantumleap33** [comment]
Ah, I knew I had mentioned it somewhere. Thanks, @JeanPaiva.
