### ISSUE TITLE
Font issues with Chrome on mobile devices

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generatepress#388]
There seems to be an issue that is reported also in the forum for the fonts.

There seems that in some parts of the websites ( random ) created with generatepress & gutenberg some font are smaller other are bigger etc.

Also this is happening with some woocommerce buttons.

You can easily check this issue as it happens with your domain generatepress.com

What you have to do is to check from a mobile and chrome ( on firefox or other browsers even facebook browser all seem alright )

David had responded that this is an issue with some xiaomi devices.

Even if I have noticed this issue with 3 xiaomi devices this looks to happen with GP GB sites and the issue has been started when you implemented the new font management system.

Before everything was working right.

This issue from then - even after a dozen of chrome updates still there.

**Comment by JeanPaiva** [comment]
@FunkyCss we will take a look at this issue, thank you for pointing out.

**Comment by diggeddy** [comment]
@FunkyCss Is this related to this topic?
https://generatepress.com/forums/topic/new-issue-with-dynamic-fonts/

**Comment by FunkyCss** [comment]
@diggeddy  No this is not related - with this specific issue. 

Is this one - > https://generatepress.com/forums/topic/gp-typografy-bugs-on-mobile/

**Comment by FunkyCss** [comment]
Maybe the chrome browser has some issue and I am not sure if this is actually GP fault. 

But that thing did not happened previously as I have noticed in the forum topic.

So I thought I should mention this one - I will send you images from your own site how it looks in specific devices with Chrome and in firefox ( Chrome in Xiaomi Devices )

**Comment by diggeddy** [comment]
All the theme does is write the CSS for setting the font-family and the applicable styles.
This issue is how specific browsers on specific manufacturer OSes handle font rendering, and this is not something the theme has any control over.
