### ISSUE TITLE
Show site title and description on sticky navigation

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#397]
Again, one of those things that, even if there is a code solution, it would definitely help to integrate inside the Customizer. An option to show the site title and description when sticky navigation is active. Could be in the form of checkboxes in Layout -> Sticky navigation inside the Customizer.

**Comment by fernandoazarcon2** [comment]
+1 from user

**Comment by SchneiderSam** [comment]
@fernandoazarcon2 I think it's a waste to put too much energy into developing customizer-navigation. Surely this has no future for FSE!? I would find it much cooler if you work on a solution (maybe an element?!) with which you can create a navigation individually with GB and GP.

**Comment by diggeddy** [comment]
the Theme already has too many separate navigation configurations, a lot of which need a complete refactor.
Closing this issue as it will be resolved in future GP Premium elements.
