### ISSUE TITLE
Admin styles are lost on responsive preview

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#399]
### Description
Admin styles seem to be lost when previewing on tablet and mobile.

### Steps to reproduce
1. Create a CSS file with some styles for the admin. In my case, I used `@font-face` to import some fonts which I had uploaded to my child theme.
2. Create a page and add some simple text.
3. Import the stylesheet in the admin. For example:

```
function admin_style() {
  wp_enqueue_style('admin-styles', get_stylesheet_directory_uri().'/admin.css');
}
add_action('admin_enqueue_scripts', 'admin_style');
```

#### Actual behavior
Previewing on tablet and mobile loses the imported styles. Desktop preview is fine.

#### Expected behavior
Previewing on tablet and mobile should display the text in the imported font.

**Comment by tomusborne** [comment]
This is because the editor uses an iframe for responsive views, so those enqueued styles aren't added to the iframe.

You need to use the `block_editor_settings_all` filter to add CSS to the content area itself.

**Comment by quantumleap33** [comment]
Hmmm, strange, I just tested on a relatively older local site. I've updated WP version number, GP, GPP, GB and GBPro and now they display fine!

**Comment by quantumleap33** [comment]
Ah no, it's because this one works instead:

```
add_filter( 'generate_editor_styles', function( $editor_styles ) {
    $editor_styles[] = 'fonts.css';
    return $editor_styles;
} );
```
