### ISSUE TITLE
Custom headers is outside of header tag

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#41]
I've trying to achieve POSH HTML5 and I see that the `<header></header>` is missing an `H1` element required by specification from W3C. Does the whole theme need to be modified for a conditional and wrap it within the header tag?

https://denverprophit.us/social-media/social-media-strategy-crowdsourcing-information/

I'll fix the redirects later.
```
<div class="inside-page-header">
    <h1>Social Media Strategy With Crowdsourcing Information</h1>
</div>
```

**Comment by tomusborne** [comment]
I assume you mean the `.entry-meta` header? Typically it would hold the `<h1>`, but it's not since you're using the page header.

I'll look into changing the `<header>` element if the page header is in use.

**Comment by tomusborne** [comment]
I've moved this to our private GPP repo. Thanks!
