### ISSUE TITLE
Improve Underline Links functionality in the Customizer

### ISSUE THREAD

**Issue by quantumleap33** [tomusborne/generatepress#413]
Currently, the `Underline Links` functionality affects all links on the page. A usual and accessible WP design most of the time requires underline links not to be applied in areas other than the main content.

I propose some options in the Customizer that could exclude underlining from:

- Sidebar links
- Footer links
- Post meta links
- Comment form meta links

In addition, I propose for GB elements to have a typography option to include/exclude underlining.

**Comment by SchneiderSam** [comment]
Like the idea!

**Comment by diggeddy** [comment]
Closed for same reasons as:
https://github.com/tomusborne/generatepress/issues/311
