### ISSUE TITLE
Extend Global Colors sections?

### ISSUE THREAD

**Issue by andrewdodson14** [tomusborne/generatepress#414]
I’m curious if there’s a way to extend the Global Colors sections (Body, Top Bar, Header, Primary Navigation, etc.) to include additional sections/options?

---

[#### References](https://docs.generatepress.com/article/global-colors-overview/)

**Comment by andrewdodson14** [comment]
Thank you! I will give this a try.

**Comment by JeanPaiva** [comment]
Closing this issue, feel free to open it again if you need be.

**Comment by andrewlouder** [comment]
I'd like to reopen this if I can. I'm finally getting around to fully testing this. When I have the Customizer open and I change one of my custom colors, the live preview works and shows my changes. But after I publish and close out of the Customizer, my color changes go away. When I reopen the Customizer, the color I chose originally is still selected, but it's not applied to my element.

**Comment by JeanPaiva** [comment]
Ah sorry @andrewdodson14 forgot we have to generate the CSS for your custom controls.

Try adding this action after the one above:

```php
add_action( 'generate_colors_css', 'gp_add_custom_colors_css', 15 );
function gp_add_custom_colors_css( $css ) {
	$settings = wp_parse_args(
		get_option( 'generate_settings', array() ),
		generate_get_color_defaults()
	);

	$css->set_selector( '.my-custom-selector' );
	$css->add_property( 'color', $settings['custom_text_color_key'] );

	$css->set_selector( '.my-custom-selector:hover' );
	$css->add_property( 'color', $settings['custom_text_color_hover_key'] );
}
```

You can change/add more CSS properties, just remember to always set the selector before adding the property :)
