### ISSUE TITLE
Elements - Margins set on GB blocks not respected in editor when choosing sidebar block element type

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generatepress#418]
### Description
Margins set on GB blocks like container and headline and not shown in the editor when editing a block element set to sidebar right or left. If I switch to another block element type the margins set on the GB blocks are then shown correctly. So the behaviour seems specific to any GB blocks within a sidebar type block element. The margins set also seem to show on the front-end correctly, so it appears to be just the editor view which is incorrect.

### Steps to reproduce
1. Create a new block element assigned to sidebar left of right
2. Add some GB containers and headlines and apply margin settings
3. See if the margins are shown in the editor

Thanks

**Comment by tomusborne** [comment]
This is a known issue that is fixed in GPP 2.2.0. We should have public testing available soon.

Thanks!

**Comment by eastriverstudio** [comment]
@tomusborne ok thanks, is there any update on the upcoming GPP 2.2.0 public testing/release?
