### ISSUE TITLE
Host Fonts Locally

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generatepress#419]
With the latest news we hear from Wordpress contributora, WP probably will ask from theme devs to implement the google fonts locally.

Is going GP this way? This sounds good in terms of performance ( I guess ) and is going to solve some issues there might be.

---

https://wptavern.com/wordpress-theme-authors-are-moving-to-host-fonts-locally

**Comment by diggeddy** [comment]
Our understanding is that WP will not allow themes to load Fonts ( like all other assets ) from an external resource.
By default GeneratePress does not load any external fonts, as it only loads the System Stack.
Our plans are:

1. GeneratePress - Add a privacy notice in Customizer > Typography when selecting a Google font. This will inform users what affect this may have on user privacy
2. GeneratePress Premium - A new Local Font Library feature. Allowing uses to install external fonts locally.

**Comment by FunkyCss** [comment]
Hallo David,

Thanks the premium feature sound awesome!
