### ISSUE TITLE
Yoast Breadcrumbs gone missing

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#42]
After the 2.x update, my yoast breadcrumbs have gone missing. Are they missing in your dev environment?

**Comment by tomusborne** [comment]
How did you have them added?

**Comment by inetbiz** [comment]
Plugin activated. Titles & Post Options for Breadcrumbs. On post, show category. The only part that is showing breadcrumbs is my Q&A CPT because I added the function call to it.

**Comment by tomusborne** [comment]
GP doesn't support breadcrumbs by default - you need to add the function they provide into the template/hooks. Did you have the code added before?

**Comment by inetbiz** [comment]
I'll go back and check. You sure that's wise NOT supporting one of the most used plugins on earth?

**Comment by inetbiz** [comment]
https://docs.generatepress.com/article/generate_header/ I don't see a hook to manipulate what's inside the `<header></header` I see a before and after hook.

**Comment by tomusborne** [comment]
There's these two hooks:
https://docs.generatepress.com/article/generate_before_header_content/
https://docs.generatepress.com/article/generate_after_header_content/

It only takes a minute to add the breadcrumbs wherever you like using hooks, so we've never found it necessary to add more options to the theme for it.

**Comment by inetbiz** [comment]
If you have content for script goodies like genesis does, that'd be a good place. Yah I went back and wrote a hook to get it back.
