### ISSUE TITLE
External Call to US - necessary?

### ISSUE THREAD

**Issue by masteradhoc** [tomusborne/generatepress#423]
### Description
Checking out sites with https://www.violating-gdpr.com/ to check if there are some external calls outside Europe.
We want to comply with GDPR and found this call on GP Sites.

![image](https://user-images.githubusercontent.com/6242098/185797104-6481ee1a-11c4-4a11-b73b-221d75bbd5aa.png)

### Steps to reproduce
1. open https://www.violating-gdpr.com/
2. enter https://generatepress.com
3. Check call to gmpg.org

#### Expected behavior
is this call to gmpg.org still needed? i know in some earlier themes also wordpress did it itself.
but seems in the last three themes its gone also there, reference:
- https://github.com/WordPress/twentytwentythree
- https://github.com/WordPress/twentytwentytwo
- https://github.com/WordPress/twentytwentyone

Would be amazing if we could remove this and nothing would change ;)

**Comment by JeanPaiva** [comment]
@masteradhoc we will be removing that call on our next version. Thanks for pointing that out :)
