### ISSUE TITLE
Bug on the product stars ( reviews ) on the related products

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generatepress#431]
### Description

There seem to be an issue on related products when they have been reviewed.

There seem to show the stars and bellow them the number of the rating ( 5.00, 4.67, etc )

This issue seem to be old on my GP sites and have not been resolved yet, not sure if is a woocommerce issue but when I changed the theme to onother 

### Steps to reproduce

Add some related products and make some different kind of ratings 

#### Actual behavior

You see some numbers too ( check print screen )

#### Expected behavior

You should see only the stars.

![5-9-2022_MxxJoSnl1j](https://user-images.githubusercontent.com/62518751/188181748-da545ed1-dbc1-48c2-bd8e-327539f4b6a4.jpeg)

**Comment by FunkyCss** [comment]
<span style="width:100%"><strong class="rating">5.00</strong> out of 5</span>

This is the markup where it happens

**Comment by FunkyCss** [comment]
Checked again this and it seems that I cant recreate in other template than " Merch "

There seem to be a css that breaks things there.

I will investigate further and will reply back.

**Comment by diggeddy** [comment]
Closing as cannot replicate issue.
