### ISSUE TITLE
Abilitiy to disable individual tabs of layout metabox

### ISSUE THREAD

**Issue by emilostervig** [tomusborne/generatepress#44]
Before 2.0 it was possible to hook out individual metaboxes, that was not needed for the project.

With the new tabbed metabox, it's not possible to only remove some components. The entire metabox is either removed or kept.

It would be really nice to be able to remove selective components via hooks.

Also, is this the best forum to inform you of bugs, or should i go somewhere else with it? I have noticed an issue with dropdown.js post 2.0.

**Comment by tomusborne** [comment]
I agree - this is a needed feature. Currently it's possible by hooking CSS into the admin, but a filter would be better.

As for the bug, you can use issues here or you can use our support forum.

Thanks!

**Comment by luizbills** [comment]
I suggest a filter to add and remove new tabs, as well an action to render the content of each tab. So we can easily extend the gp metabox, without the need to create several more. Similar to what WooCommerce does.
http://www.remicorson.com/mastering-woocommerce-products-custom-fields/

**Comment by tomusborne** [comment]
This is possible now: https://generatepress.com/forums/topic/is-it-possible-to-extend-the-layout-metabox/#post-552244
