### ISSUE TITLE
Separator gets wrong colour if --text CSS variable exists

### ISSUE THREAD

**Issue by gabbsmo** [tomusborne/generatepress#445]
### Description
I found that if I define a colour variable "--text" in GP it will cause separator blocks to always have that colour, instead of what you defined in the editor. I thought this was an issue with WP or Gutenberg but they insists that this is a bug in GeneratePress.

Can someone from the GP team weigh in on this?

#### References
https://github.com/WordPress/gutenberg/issues/38729
https://generatepress.com/forums/topic/separator-color-not-working-in-front-end/

**Comment by diggeddy** [comment]
See my reply to your guteneberg issue.

Closing here as its not a theme related issue.
