### ISSUE TITLE
Elements - new loop template element issue when columns previously enabled

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generatepress#447]
### Description
I've been testing out the new loop template in the Alpha. Testing this out it works well and I love that I can now override the loop template with Elements. I have noticed one slight issue with the current implementation if the column settings has been activated in the customiser on blog settings or on custom post types via the filter `generate_blog_columns`. 

If the column setting is left on for the blog post or CPT archive the loop template targets the template gets placed inside the original columns wrapper `generate-columns-container` which has display: flex applied so it mucks up the query loop's grid display when there isn't enough columns to fill the row.

Also I experienced some strange alignments with the outer container I'd placed the query loop block within to create some padding, I assume that might also be because of the display: flex.

#### Expected behavior
Unless there's a good reason for keeping the `generate-columns-container` wrapper when a loop template is active that I've not thought of, if a loop template is active on the archive the columns wrapper should be removed so we can set and style our own container to hold the query loop block.

**Comment by tomusborne** [comment]
Thanks for this! Customizer columns will now automatically be turned off when using a Loop Template in the next update.
