### ISSUE TITLE
Navigation $classes and PHPDoc

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#45]
@tomusborne 

https://github.com/tomusborne/generatepress/blob/master/inc/markup.php#L361
```
function generate_navigation_classes( $classes ) {
		$classes[] = 'main-navigation';
		// Get theme options
		$generate_settings = wp_parse_args(
			get_option( 'generate_settings', array() ),
			generate_get_defaults()
		);
		$nav_layout = $generate_settings['nav_layout_setting'];
		if ( $nav_layout == 'contained-nav' ) {
			$classes[] = 'grid-container';
			$classes[] = 'grid-parent';
		}
		return $classes;
	}
}
```

links to https://github.com/tomusborne/generatepress/blob/master/inc/element-classes.php#L234

```
/**
	 * Display the classes for the navigation.
	 *
	 * @since 0.1
	 * @param string|array $class One or more classes to add to the class list.
	 */
```

My IDE is barking about phpdoc params in https://github.com/tomusborne/generatepress/blob/master/inc/markup.php#L361

Is my IDE setup wrong or the function is incomplete?

**Comment by tomusborne** [comment]
Ah yes, those are missing `@param` entries in the comments. I'll get those added in.

Thanks!

**Comment by inetbiz** [comment]
I was running PHPStorm code analyzer on the project fork. I'm not strong enough with PHPDoc to fix it, myself.

**Comment by tomusborne** [comment]
We'll be deprecating these functions in 2.2 for a new attribute system.
