### ISSUE TITLE
Possible Page Edit issue related with WooCommerce

### ISSUE THREAD

**Issue by atmostfear-entertainment** [tomusborne/generatepress#479]
### Description

Since updating GeneratePress to the latest 3.2.2, the preview remains boxed instead of full width when clicking to edit a page. While downgrading the theme, the issue does not reproduce, and everything displays correctly.

### Steps to reproduce

We are uncertain. However, when installed and active, it appears to be related to WooCommerce. Unfortunately, we have troubleshot by disabling all plugins, switching from our child theme to the default theme, and the issue persists.

We have also checked our containers, settings, Customizer, and everything we could think of, and the issue remains.

#### Actual behavior

![Screenshot 2022-11-17 at 08-25-10 Edit Page “Arts Cultures Events and Reviews” ‹ Atmostfear Entertainment — WordPress](https://user-images.githubusercontent.com/34287288/202458400-83babc90-2cc3-45a8-b8fb-d4e7df5f07b3.png)

#### Expected behavior

Preview with full width when editing the page.

#### References

The issue has been reported on the official Facebook Group, and others face the same problem when running WooCommerce.

**Comment by tomusborne** [comment]
Turns out this issue here was a CSS parsing error caused by spaces in the global color variables.

**Comment by atmostfear-entertainment** [comment]
Dear @tomusborne,

We appreciate the fact you personally assist us finding, and correcting this issue for us while debugging it. Which is now is resolved due to your involvement.

On behalf of our team, many thanks.
