### ISSUE TITLE
GP Premium Deactivation Function

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#48]
I noticed there wasn't a deactivation function to remove it from the database. I'd also like to propose something like...

```
add_filter( 'plugin_action_links', 'generate_add_action_plugin', 10, 5 );
function generate_add_action_plugin( $actions, $plugin_file )
{
	static $plugin;

	if (!isset($plugin))
		$plugin = plugin_basename(__FILE__);
	if ($plugin == $plugin_file) {

		$site_link = array('support' => '<a href="https://generatepress.com/support/" target="_blank">Support</a>');
		$purchase = array( 'Purchase' => '<a href="https://generatepress.com/?ref=667" target="_blank">Purchase</a>');

		$actions = array_merge($purchase, $actions);
		$actions = array_merge($site_link, $actions);

	}

	return $actions;
}
```
Something like that and with assets to affiliates. I plan on forking your theme and including the plugin to go purchase.

**Comment by tomusborne** [comment]
If they have GP Premium activated, the purchase link would be redundant, wouldn't it?

A database clean up option is a good idea - I've added that as an issue in our GPP repo.
