### ISSUE TITLE
I want a hook to put stuff directly on the right side on the hamburger menu. Not just in the middle. 

### ISSUE THREAD

**Issue by a4jp-com** [tomusborne/generatepress#482]
### Description
I want a hook to put stuff on the right side on the hamburger menu. Not just in the middle. There is one for the right side but not left without it being pushed into the middle. I want a super easy way to put a button on either side of the hamburger menu on my client's site.
---

**Comment by diggeddy** [comment]
Wont fix.
Can be achieved using existing hooks such as `menu_bar_items`
