### ISSUE TITLE
Global Color CSS `.has-{slug}-background-color` and `.has-{slug}-color` rules are not specific enough.

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#489]
### Description
the `.has-{slug}-background-color` and `.has-{slug}-color` are not specific enough to overcome some theme styles.
A common example is that the Buttons Block link `color` inheriting its styles from the themes `.inside-article a` styles.

To correct these we could add either:

A. Use `!important` :

` .has-base-3-color {
    color: var(--base-3) !important;
}`

B. Increase specificity:

`:root .has-base-3-color {
    color: var(--base-3);
}`

My preferred approach would be option B.

**Comment by tomusborne** [comment]
@diggeddy Should we use `:root` or something like `body`?

**Comment by diggeddy** [comment]
`body .has-base-3-color` and  `.inside-article a`  have the same specificity - so the `has-` styles would have to be loaded later.
Whereas `:root` has a higher specificity than `body` so it would win wherever it was loaded.

Do we have any concerns using `:root` other than we have only used them for variables ?
