### ISSUE TITLE
Improve generate_padding_css()

### ISSUE THREAD

**Issue by tomusborne** [tomusborne/generatepress#49]
Awesome suggestion here: https://generatepress.com/forums/topic/suggested-generate_padding_css-improvement/#post-462404

Needs testing.

**Comment by SimonPattzone** [comment]
I'm the author of the linked forum post.
I have had another look at the function, and have come up with the following:

I would suggest a change of function name to something like 'shorthand_css_values' as it can be used for any quad css value that can be shorthanded, not just padding.

I have simplified the shorthanding code and changed from using absint to intval to allow negative values.
Note that only integer values are returned.

Obviously it only returns 'px' values, so if you have plans to allow em/rem/%/fr units in the future then it'll need changing.

It behaves correctly with any/all values passed to it:
'10', '10px', '10em', '10%', '10.12' will all result in '10px'.
'-10', '-10px', '-10em', '-10%', '-10.12' will all result in '-10px'.
'10.23', '10.23px', '10.89%' will all result in '10px'
'0px', '0em', '0.5px', 'asd' will all result in '0'

`function shorthand_css_values( $v1, $v2, $v3, $v4 ) {

	// prepare the values
	$v1 = ( intval( $v1 ) <> 0 ) ? intval( $v1 ) . 'px ' : '0 ';
	$v2 = ( intval( $v2 ) <> 0 ) ? intval( $v2 ) . 'px ' : '0 ';
	$v3 = ( intval( $v3 ) <> 0 ) ? intval( $v3 ) . 'px ' : '0 ';
	$v4 = ( intval( $v4 ) <> 0 ) ? intval( $v4 ) . 'px ' : '0 ';

	// shorthand the values
	if ( $v2 === $v4 ) {
		$v4 = '';				// v2 == v4, only need 3 values
		if ( $v1 === $v3 ) {
			$v3 = '';			// v2 == v4 && v1 == v3,  only need 2 values
			if ( $v1 === $v2 ) {
				$v2 = '';		// v1 == v2 == v3 == v4, only need 1 value
			}
		}
	}

	// remove final trailing space;
	return trim( $v1 . $v2 . $v3 . $v4 );
}`
