### ISSUE TITLE
PHP error ( Deprecated Notice ) 

### ISSUE THREAD

**Issue by FunkyCss** [tomusborne/generatepress#496]
I am using the plugin Query Monitor to test a new Generatepress Site, 

And I have this kind of notice from this plugin 

**PHP errors ( Deprecated Notice )** 

Deprecated - stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated

wp-includes/functions.wp-styles.php:90
stripos()
wp-includes/functions.wp-styles.php:90
wp_add_inline_style()
wp-content/plugins/gp-premium/menu-plus/functions/generate-menu-plus.php:735
generate_menu_plus_enqueue_css()
wp-includes/class-wp-hook.php:308
do_action('wp_enqueue_scripts')
wp-includes/script-loader.php:2180
wp_enqueue_scripts()
wp-includes/class-wp-hook.php:308
do_action('wp_head')
wp-includes/general-template.php:3043
wp_head()
wp-content/themes/generatepress/header.php:16
load_template('wp-content/themes/generatepress/header.php')
wp-includes/template.php:718
locate_template()
wp-includes/general-template.php:48
get_header()
wp-content/themes/generatepress/page.php:17

**Comment by JeanPaiva** [comment]
@FunkyCss thank you. It is already fixed by https://github.com/tomusborne/generatepress/pull/485

Will be released with GP 3.3.
