### ISSUE TITLE
Warning Deprecated: preg_replace() in 6.2-beta2 PHP 8.1

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#513]
### Description
6.2-beta2 PHP 8.1
Generate press theme 3.2.4

`Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /public_html/blog/wp-admin/includes/plugin.php on line 2088`

Reported here:

https://generatepress.com/forums/topic/php-8-1-deprecated-warning-preg_replace/#post-2537770

**Comment by tomusborne** [comment]
I believe this is a core notice, not GP.
