### ISSUE TITLE
GP Premium spacer isn't controlling content single

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#52]
I own premium. I created a post with full layout but I still want padding. I'm unable to control customizer container padding at https://test.denverprophit.us/2018/01/12/hello-world-2/

**Comment by inetbiz** [comment]
I had to add
```
.full-width-content.separate-containers .inside-article {
    padding: 28px;
}
```
To get some spacing and keep the background.

**Comment by tomusborne** [comment]
The Page Builder Container options are meant to remove padding, as it's typically added by the page builder. In order to keep it, the CSS you provided is necessary.
