### ISSUE TITLE
Consider Bunny Fonts as Google alternative

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#520]
### Description
https://fonts.bunny.net/about 
provide a possible GDPR friendly method of adding fonts in the Customizer.

Lets review

**Comment by masteradhoc** [comment]
@diggeddy please embed it locally instead. That would be the proper way - bunnyfonts is just a workaround :)

**Comment by diggeddy** [comment]
Wont fix.
Integrating with 3rd party services not a good idea

**Comment by adam-aido** [comment]
@diggeddy isn't a Google Fonts also a 3rd party service? ;)
