### ISSUE TITLE
Elements - Block element editor width bug in GP 3.3.0 & GPP 2.3.0

### ISSUE THREAD

**Issue by eastriverstudio** [tomusborne/generatepress#525]
When creating a block element such as a content template or loop template the editor preview width setting is not being respected. If I set to 100% width it initially previews to 100% correctly, but then after making changes and/or refreshing it reverts back to the default width again even though 100% still shows in the block element's settings panel. Editing again reverts but it is constantly switching back to the default width for me.

Thanks

**Comment by eastriverstudio** [comment]
Updating the issue with some extra info as the bug seems to relate to GB grids and not all containers. Outer containers normally continue to stretch full width but nested grids do not until you edit the editor width setting again, but this is only temporary as coming back to the editor the width reverts again as per the screenshot.
<img width="1474" alt="CleanShot 2023-03-29 at 13 12 08@2x" src="https://user-images.githubusercontent.com/37620756/228532292-692a3d6e-a634-48de-ba51-77f1c14a8b16.png">

So not sure if this is a GP or GB issue?

**Comment by tomusborne** [comment]
Thanks for the heads up! Looks like a bug in GPP. Will be fixed in 2.3.1.
