### ISSUE TITLE
Feature: GP Premium - Store *.json in uploads folder

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#55]
Around line 82 of `/plugins/generatepress_premium/import-export/functions/functions.php` `generate_process_settings_export()` use something like wp_uploads_dir() with the parms to create `/wp-content/uploads/gp-json/` if not exist.

Dynamically generate an array of active sub-parts for customizer. json import the array of files or export to that folder. And, have a new button at the bottom for import all and also a hook action to automate for child theme authors.

**Comment by tomusborne** [comment]
It shouldn't be necessary to actually store the file on the server, as it's downloaded to your computer.

GPP 1.6 has an export all feature.

Thanks!
