### ISSUE TITLE
Undefined index notices

### ISSUE THREAD

**Issue by lutrov** [tomusborne/generatepress#56]
I'm getting a number of "undefined index" error notices which seem to be generated by the `generate_get_setting()` function:

`[05-Feb-2018 00:42:43 UTC] PHP Notice:  Undefined index: dynamic_css_cache in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

`[05-Feb-2018 00:42:46 UTC] PHP Notice:  Undefined index: dynamic_css_cache in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

`[05-Feb-2018 00:42:46 UTC] PHP Notice:  Undefined index: font_awesome_essentials in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

`[05-Feb-2018 00:42:46 UTC] PHP Notice:  Undefined index: dynamic_css_cache in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

`[05-Feb-2018 00:42:47 UTC] PHP Notice:  Undefined index: retina_logo in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

`[05-Feb-2018 00:42:47 UTC] PHP Notice:  Undefined index: font_awesome_essentials in ....\wp-content\themes\generatepress\inc\theme-functions.php on line 28`

I think this line:

`return $generate_settings[$setting];`

Should probably say this:

`return isset($generate_settings[$setting]) ? $generate_settings[$setting] : false;`

**Comment by tomusborne** [comment]
Since that option has a [default](https://github.com/tomusborne/generatepress/blob/2.0.2/inc/defaults.php#L53), it shouldn't throw a notice since the function [checks for defaults](https://github.com/tomusborne/generatepress/blob/2.0.2/inc/theme-functions.php#L23-L26).

Are you filtering the defaults by chance?

**Comment by lutrov** [comment]
Sorry, my mistake. You're correct, there __was__ a filter in one of the (many) plugins running on the client's site.

**Comment by tomusborne** [comment]
No problem!
