### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null at back-to-top.min.js?ver=2.0.2:1

### ISSUE THREAD

**Issue by jokr0815** [tomusborne/generatepress#57]
Hi,

on my page [https://teutonia-grossenlueder.de](https://teutonia-grossenlueder.de) there is an issue with the back-to-top button. 
It is not showing the back-to-top button, though it is active.
If I check the source, I can see the following error: 

> __Uncaught TypeError: Cannot read property 'addEventListener' of null at [back-to-top.min.js?ver=2.0.2:1](https://github.com/tomusborne/generatepress/blob/master/js/back-to-top.js)__

for code part

```javascript
e = document.querySelector(".generate-back-to-top");
        e.addEventListener("click", function(i) {
            i.preventDefault(),
            t(document.body, e.getAttribute("data-scroll-speed") || 400)
        }, !1)
```

Kind regards
Jo

**Comment by jokr0815** [comment]
Hi,
i found out this is cause by having NextGEN active.
But I'm not sure whether it is a template or NextGEN issue.
Kind regards
Johannes

**Comment by tomusborne** [comment]
This is something weird that NextGen does. You can grab the solution here: https://generatepress.com/forums/topic/back-to-top-button-missing/#post-478529

**Comment by jokr0815** [comment]
Hi,

the Workaround did resolve it.

Could you please have a look at this aswell? Is there a similar Workaround?
[Slide-out menu not showing sub-menu](https://generatepress.com/forums/topic/slide-out-menu-not-showing-sub-menu/)

Shall I open a new issue here?
I've already opened a thread at [NextGEN Forum](https://wordpress.org/support/topic/nextgen-conflict-with-generatepress-slideout-menu/)

Thanks and best regards
Jo

**Comment by tomusborne** [comment]
The back to top button should be fixed now. We added a new hook above `wp_footer`, so NextGen can't alter the output of it.

The slideout navigation will have to be hooked into the same area, but we have to wait a bit for people to update to 2.1.

You can find a workaround here: https://generatepress.com/forums/topic/problem-with-slide-menu-after-update/#post-536764
