### ISSUE TITLE
FR: More control typography in WooCommerce

### ISSUE THREAD

**Issue by fxaviers** [tomusborne/generatepress#58]
The same options that are available in Headings (fonts, variants, size and line height) could be available in all elements of WooCommerce: title product, price, buttom and description, for archives page and simple product page.

Yes, this is easy to be solved by CSS, but if have a native option it is much better.

**Comment by tomusborne** [comment]
I agree - some more can be done here. I've moved this to our private GPP repo.

Thanks!
