### ISSUE TITLE
Add support for font fallbacks for custom fonts

### ISSUE THREAD

**Issue by simkoG** [tomusborne/generatepress#580]
### Description
GeneratePress offers the fantastic capability to utilize custom fonts on our websites. However, there is a significant limitation in that we are unable to specify fallback fonts for these custom typefaces.

Presently, when a custom font is applied to the `body` tag, the generated CSS code appears as follows:
```
body, button, input, select, textarea {
      font-family: Gabarito;
}
```

The correct way to specify custom fonts for a website should be:
```
body, button, input, select, textarea {
      font-family: Gabarito, sans-serif;
}
```

It would greatly benefit the user experience to have an option within the Font Manager section where we can designate fallback fonts for custom typefaces.

![image](https://github.com/tomusborne/generatepress/assets/10430702/72ce936c-1145-4238-b5a3-84ee6406f7d6)

---

#### References

- I've come across a previous feature request that raised this issue; however, it was closed without any further progress. https://github.com/tomusborne/generatepress/issues/84 
- https://www.w3schools.com/css/css_font_fallbacks.asp
- https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by diggeddy** [comment]
This is already possible.

The `font family name` field accepts any value you can add to a `font-family` property including a `font stack`. 
For example:`Gabarito, sans-serif` or `Gabarito, system-ui, sans-serif`

You could also do this with Google Fonts, by fist adding a google font, and then adding a font stack.

`<img width="403" alt="Screenshot 2023-10-24 at 12 52 14" src="https://github.com/tomusborne/generatepress/assets/30641942/6e9ff11d-40de-41b8-8c69-ada3b4d7bcec">`
