### ISSUE TITLE
generate_font_option_defaults filter does not seem to work

### ISSUE THREAD

**Issue by cristovaov** [tomusborne/generatepress#587]
### Description
In a child theme, I've added a filter to set a default font family, body font size and paragraph margin. These new values are not being taken over when I go in Customizer -> Typography and not found when I use the browser inspector.

I have the  GeneratePress theme installed. GP Premium, Generateblocks and GenerateBlocks Pro activated.

### Steps to reproduce
1. In a child theme add the following filter:
```
add_filter( 'generate_font_option_defaults', 'custom_font_option_defaults' );
function custom_font_option_defaults( $defaults ) {
  $defaults['fontFamily'] = 'Archia';
  $defaults['body_font_size'] = '20';
  $defaults['paragraph_margin'] = '0';

  return $defaults;
}
```
2. Visit the customizer and go the Typography section, or visit the website and use the browser inspector.

#### Actual behavior
None of the changed values are taken,  GP's defaults remain in place.

#### Expected behavior
The defaults should change to the values set in the filter.

---

#### References
`generate_font_option_defaults` filter found in `inc/defaults.php`.

**Comment by diggeddy** [comment]
That filter has been deprecated in the later releases GP 3.1
If you're using Dynamic Typography see here:
https://docs.generatepress.com/article/dynamic-typography-overview/

Then you don't need to filter
In the Font Manager -> Add Font. Add the name of the Font Family
Now you will see your font in the Typography.

**Comment by cristovaov** [comment]
Ok clear. Thank you for clarifying!
