### ISSUE TITLE
Constant DISALLOW_FILE_EDIT set to false prevents php execution in Elements

### ISSUE THREAD

**Issue by seamofreality** [tomusborne/generatepress#589]
### Description

This is regarding GeneratePress Version 3.3.1

We've had php execution enabled in our custom theme elements defined via "Elements".
The plugin "Defender" added a line `define( 'DISALLOW_FILE_EDIT', false );` in the `wp-config.php` which led to all the snippets containing php being broken. Custom elements showed a hint: "Unable to execute PHP as DISALLOW_FILE_EDIT is defined."

![Screenshot_2023-12-29_081025@2x](https://github.com/tomusborne/generatepress/assets/4711781/3b5d3b64-ba54-4e3a-ac4a-257f4ca86be5)

### Steps to reproduce
1. Add `define( 'DISALLOW_FILE_EDIT', false );` to your `wp-config.php`

OR

1. Activate Defender plugin
2. Store normal settings with "Disable the file editor" inactive

#### Actual behavior
`DISALLOW_FILE_EDIT` set to `false` disables php execution. 

#### Expected behavior
`DISALLOW_FILE_EDIT` set to `false`  should not disable php execution, only if it's set to `true`.

---

#### References
![Screenshot_2023-12-29_081219@2x](https://github.com/tomusborne/generatepress/assets/4711781/85b9ef85-4c8f-45cb-b02a-3b80a692a8e5)

**Comment by tomusborne** [comment]
This will be fixed in GPP 2.5.0.

Thanks!
