### ISSUE TITLE
Alternative .org domain

### ISSUE THREAD

**Issue by glidingthrough** [tomusborne/generatepress#591]
### Description
When looking into GeneratePress, I first went to a (presumably fraudulent) generatepress.org domain before discovering the real .com domain. Figured you should be aware in case you wish to flag it as abuse to the domain registrar.

### Steps to reproduce
Search GeneratePress on DuckDuckGo.

#### Actual behavior
Potential users directed to incorrect domain and duped into parting with their cash; potential unauthorised re-distribution.

#### Expected behavior
No bad guys.

---

#### References
Not linking to it directly in case they actively monitor traffic source.

**Comment by tomusborne** [comment]
Thanks for this - we are actively pursuing this.
