### ISSUE TITLE
Filter css outputs

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#6]
Example: https://github.com/tomusborne/generatepress/blob/master/functions.php#L518-L520

`do_action( 'generate_base_css', $css );` is useful to add more css, but not to remove or erase.

Changing `return $css->css_output();` to `return apply_filters( 'generate_base_css_output', $css->css_output() );` it will be very useful to remove or change styles.

**Comment by tomusborne** [comment]
Good idea - I might do both.

Won't be in the upcoming bug fix update (within the hour) as I don't have time to fully test, but will be in the next main update.

Thanks!

**Comment by luizbills** [comment]
You're welcome. If you need some beta tester, I can help :)

**Comment by tomusborne** [comment]
Any particular reason you would want to remove CSS from the output? Doing so would break Customizer functionality for whatever you remove?

**Comment by luizbills** [comment]
I once had to remove the generated color to `a:visited`. But I ended up using `a:visited { color: unset }`. Even so (in my opinion) this functionality will be very useful. 
About breaking some customizer functionality, I do not know to answer you.

**Comment by tomusborne** [comment]
Any example code of how you would remove that with a filter?

**Comment by luizbills** [comment]
add_filter( 'generate_base_css_output', 'my_function' );
function my_function ( $output ) {
    // remove the global `a:visited` occurrences
    return str_replace( 'a, a:visited', 'a', $output );
}

**Comment by tomusborne** [comment]
https://github.com/tomusborne/generatepress/commit/cc6ed684369289b38a102407ba83d1c9736951f3

Thank you sir 👍
