### ISSUE TITLE
CSS selector too broad

### ISSUE THREAD

**Issue by tudormnt** [tomusborne/generatepress#60]
Hello,

I noticed there is a clearfix targeting class names that contain "content". This is a way too broad selector as "content" can be found in many other class names that come from plugins or other components. One example of this causing issues is in Safari when the element has display: flex. Safari doesn't ignore pseudo elements visually for flexbox and treats them as elements inside the flexbox, allocating 1px for their display. This means that for elements containing "content" in the name of the class that have "display: flex" an override needs to be added.

This is the css I'm referring to:

.clear:before,
.clear:after,
[class*="content"]:before,
[class*="content"]:after,
[class*="site"]:before,
[class*="site"]:after {
	content: '';
	display: table;
}

Hope you can find a quick solution. Thanks!

**Comment by tomusborne** [comment]
https://github.com/tomusborne/generatepress/commit/b22d4b812555c4d0f21a93c62ab195688ef3713a

Thanks!
