### ISSUE TITLE
how to change menu background color for the free version

### ISSUE THREAD

**Issue by janarth20** [tomusborne/generatepress#61]
Hi everyone,
Im using generatepress free version.
Can someone tell me how to change menu background color?
Which file i should edit to get the result?

Thanks

**Comment by leohsiang** [comment]
Hi there,

Technical questions should be posted in our free forum: https://wordpress.org/support/theme/generatepress

Thanks!

**Comment by tomusborne** [comment]
There's CSS for changing navigation colors here: https://docs.generatepress.com/article/changing-navigation-colors/
