### ISSUE TITLE
Widgets in content areas and compatibility with Page Builder by SiteOrigin 

### ISSUE THREAD

**Issue by wanderingexplorer** [tomusborne/generatepress#62]
@tomusborne @generatepress 

Here is an example of the issue. I'm sure there will perhaps be more cases too:

1) Install "Page Builder By SiteOrigin" (https://wordpress.org/plugins/siteorigin-panels/)

2) Install "SiteOrigin Widgets Bundle" (https://wordpress.org/plugins/so-widgets-bundle/)

3) Install GeneratePress

4) Activate all the above

5) Add a New Page and using the WordPress' standard editor (Visual tab) add a bullet point list.

6) View the page and you can see the standard black bullet point circles on the front end

7) Now edit the page and click on the "Page Builder" tab. It will automatically transfer the text content into its "SiteOrigin Editor" widget

8) Update the the page and view the front end again and you will see the black bullet point circles have been removed from the list

From closer inspection I can see that its due to the following CSS rule in themes/generatepress/style.min.css?ver=2.0.2

.widget ul li {
list-style-type: none;
position: relative;
padding-bottom: 5px;
}

I guess this rule was added to remove the bullet circles from the sidebar and footer widget areas? But as Page Builder is based off of using widgets, this rule is affecting page content too.

Perhaps you could make your rule a little more specific e.g. ".sidebar .widget ul li {"

Thank you :-)

**Comment by tomusborne** [comment]
https://github.com/tomusborne/generatepress/commit/d2d7f91fb8dc30dd1fc8bf485564ce0c6d1a4e81

Thanks!
