### ISSUE TITLE
Missing Google Font

### ISSUE THREAD

**Issue by VR51** [tomusborne/generatepress#66]
The Google Font Oranienbaum is missing from the Customizer typography settings.

The font is in Google here https://fonts.google.com/specimen/Oranienbaum.

The font is listed in the helper typography.php https://github.com/tomusborne/generatepress/blob/master/inc/typography.php

I tested this in several sites. The font shows as an option for none of the typography settings.

**Comment by VR51** [comment]
Resolved through the GeneratePress forum. Thank you.

Solution is found at https://docs.generatepress.com/article/customizing-the-google-font-list/

**Comment by tomusborne** [comment]
So it only worked if you added it through the filter? The one that's already in there is broken?

If so I'll re-open and will take a deeper look.

Thanks!

**Comment by VR51** [comment]
That's correct, Tom. Needed to use the filter to make the font usable.

```
add_filter( 'generate_typography_customize_list', 'tu_add_google_fonts' );
function tu_add_google_fonts( $fonts ) {
	$fonts[ 'oranienbaum' ] = array( 
		'name' => 'Oranienbaum',
		'variants' => array( '400' ),
		'category' => 'serif'
	);
	return $fonts;
}
```
