### ISSUE TITLE
SSL expired.

### ISSUE THREAD

**Issue by sahsu** [tomusborne/generatepress#68]
curl -I 'https://gpsites.co/classic/files/screenshot.png'
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html 

all preview images are gone now!

**Comment by sahsu** [comment]
[expired snapshot](https://www.dropbox.com/s/mwzhk30a3b7thce/Screenshot%202018-05-27%2017.31.10.png?dl=0)

**Comment by tomusborne** [comment]
Thanks for reporting! Should be fixed now :)
