### ISSUE TITLE
RTL CSS file - modifications

### ISSUE THREAD

**Issue by danstramer** [tomusborne/generatepress#69]
Please add this to the RTL css file of GeneratePress:
`ol, ul {
    margin: 0 3em 1.5em 0em;}`

We need the right margin on RTL lists, not the left one.

It will fix lists when viewing RTL pages.
If I have some more updates to RTL, I'll post them here.

Thanks

**Comment by danstramer** [comment]
Update to left margin for cat links icon:
`.cat-links:before, .comments-link:before, .nav-next .next:before, .nav-previous .prev:before, .tags-links:before, footer.entry-meta .author:before, footer.entry-meta .posted-on:before {margin-right:0; margin-left:.6em;`

**Comment by tomusborne** [comment]
Thanks! Will get these tweaks added to 2.2.

**Comment by danstramer** [comment]
Just noticed something strange.

The GP theme does have some of the RTL rules I stated, but I noticed that it is not loaded when I view the RTL site.

Could it be because I created an rtl.css file in my child theme?

Does the theme not load first it’s rtl.css file and them the child theme’s rtl.css file? It works this way with style.css

 

Thanks

Dan

 

/-------------------------

Dan Stramer 

Dan Media Design

www.dmdesign.co.il <http://www.dmdesign.co.il/> 

T: 647-544-2912

Skype: dan_stramer

**Comment by tomusborne** [comment]
I think the child theme `style.css` and `functions.php` files are unique in that they add to the existing parent files. Other files will overwrite the parent files.

Try naming your file something else and enqueuing it in your `functions.php`.

**Comment by danstramer** [comment]
Yes, that's probably the reason.
I'll enqueue it as you suggested.
Thanks

**Comment by danstramer** [comment]
I think there might be an issue with Polylang as it is not firing the rtl.css file from the theme (even when there is no rtl.css in the child theme). Once the site goes live I'll report back.

**Comment by tomusborne** [comment]
Just looking into this and it seems those styles do already exist in the theme. Did you ever get this figured out?

**Comment by danstramer** [comment]
Hi Tom,
I don't see these updates: https://github.com/tomusborne/generatepress/issues/69#issuecomment-398085281 in the RTL.css file (line 147)
Other updates are done.
As for Polylang as the other issues, I will check with the next install.
Thanks

**Comment by tomusborne** [comment]
https://github.com/tomusborne/generatepress/commit/d6a6e17a376e3d920ef41d50ec09d8420fbeb0e2

Thank you!
