### ISSUE TITLE
Image option "Full width"

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#74]
I downloaded 2.2 Beta.

It would be nice if you had a possibility to get the image to the edge with the image option "Full width":

![screenshot_1](https://user-images.githubusercontent.com/9355398/47524739-c0bde100-d89b-11e8-9ceb-8a84a9cb1759.png)

**Comment by tomusborne** [comment]
Right now `alignfull` will only work when no sidebars are set.

`alignwide` is what you're looking for in this instance.

It would be cool if `alignfull` acted like `alignwide` when sidebars are present though. I'll take a look at that.

**Comment by tomusborne** [comment]
Done: https://github.com/tomusborne/generatepress/commit/7ad810f228c120be7bd463813e598080d040a98b

Thanks for the idea!

**Comment by SchneiderSam** [comment]
Wowo coool. So fast :-)

But.. it's not working: http://recordit.co/XNLuP8R93I

**Comment by tomusborne** [comment]
It's cached dynamic CSS.

You can see it in the Customizer, or by saving the Customizer (make a change and change it back).

GP does this for you when the version changes, but the version isn't changing yet.

**Comment by SchneiderSam** [comment]
Uhhhh amazing. Just coool!!!

Thank you!
