### ISSUE TITLE
YouTube video does not have full width

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#77]
If I insert a Youtube video, choose no Sidebar and fullwidth, I would expect the video to be visible at full width. But it is simply left-aligned:

![screenshot_1](https://user-images.githubusercontent.com/9355398/47580456-3f278b00-d94f-11e8-9dba-895a2af94288.png)
![screenshot_2](https://user-images.githubusercontent.com/9355398/47580459-3f278b00-d94f-11e8-9a4d-e40b2b2a728f.png)

**Comment by tomusborne** [comment]
I wonder how frequently people would be doing this?

It should be fixed with something like this:

    .wp-block-video video {
        width: 100%;
    }

I hesitate to add it to the theme though, simply because I'm not sure full width videos will be a super popular thing. Thoughts?

**Comment by SchneiderSam** [comment]
Yes, it is. But if the option fullwidth is present, then I would expect that. But it's true: it's not super important. It would only look slightly flawed. But that's all.

**Comment by tomusborne** [comment]
Looking at this more, and it definitely seems to be a bug.

I wonder if it would be better to report this to the Gutenberg team though.

For example, they've included this CSS inside Gutenberg itself for images:

    .wp-block-image.alignfull img, 
    .wp-block-image.alignwide img {
        width: 100%;
    }

It seems like they might want to change it to:

    .wp-block-image.alignfull img, 
    .wp-block-image.alignwide img,
    .wp-block-video.alignfull video,
    .wp-block-video.alignwide video {
        width: 100%;
    }

Let me know if you'd rather me open an issue with them.

**Comment by SchneiderSam** [comment]
You know better than that. You go ahead and do it. I thought it was the theme. Interesting is also: when I try to insert a YouTube video on https://wordpress.org/gutenberg/ - it just doesn't work!

Check my test: http://recordit.co/p6yL6zWlza

**Comment by intochzcom2** [comment]
i am also facing same issue but my issue is resolved when i try classic revision of wordpress you can 
[visit this page](https://bestpropanegrill2020.com/best-flat-top-grills/).

**Comment by BSCShoes** [comment]
![ccc](https://user-images.githubusercontent.com/68680992/88259026-ec713380-ccda-11ea-90d0-34f366e93d7c.gif)
 i also try to insert with this setting, it just working fine please check https://bestshoeschoice.com/
