### ISSUE TITLE
Ideas for the different styles you could use in GP 2.2 and Gberg

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#79]
I have some ideas for the different styles you could use GP:

Advanced color backgrounds (Similar to the picture Option `widewidth` you could also build them to the edge.):
![screenshot_5](https://user-images.githubusercontent.com/9355398/47674359-66809100-dbb7-11e8-952d-e5abdbaf8bbc.png)

Extended quotations or paragraphs:
![screenshot_6](https://user-images.githubusercontent.com/9355398/47674431-9039b800-dbb7-11e8-8726-6d9ad6281785.png)
![screenshot_7](https://user-images.githubusercontent.com/9355398/47674463-a3e51e80-dbb7-11e8-8760-ac70e4a5d2eb.png)

Sources: 

http://preview.themeforest.net/item/narratium-simplicity-for-authors/full_screen_preview/20844434?_ga=2.217228758.1761108419.1540840096-627824593.1538096002

http://preview.themeforest.net/item/narratium-simplicity-for-authors/full_screen_preview/20844434?_ga=2.217228758.1761108419.1540840096-627824593.1538096002

http://preview.themeforest.net/item/narratium-simplicity-for-authors/full_screen_preview/20844434?_ga=2.217228758.1761108419.1540840096-627824593.1538096002

thoughts?

**Comment by SchneiderSam** [comment]
Yeah, that sounds very good, too. Is there already a list of desired blocks for the GP plugin?

**Comment by tomusborne** [comment]
Not yet - still working on something internally.
