### ISSUE TITLE
close mobile menu and slideout menu on click

### ISSUE THREAD

**Issue by luizbills** [tomusborne/generatepress#8]
Close the mobile menu (or slideout) when a menu link is clicked. It will be very useful to one page sites that scroll the screen instead of redirect to another page.

**Comment by tomusborne** [comment]
Done, thanks!

https://github.com/tomusborne/generatepress/commit/f79ae8966cad7046fe280df1f495f062caf8aac4

**Comment by luizbills** [comment]
thank you
