### ISSUE TITLE
No difference between wide and small lines.

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#80]
I use Gberg 4.2.0 RC1
And GP 2.2 Alpha-2

Here is the Bug:
![bmdavt0jjf](https://user-images.githubusercontent.com/9355398/47799209-18d86580-dd2a-11e8-86f3-c206f783e279.gif)

http://recordit.co/bmdavt0jJf

I think the wide line as it exists now would be nice for the function `wide line`. Or maybe to the edge? That would also be chic, but probably rather unusual in use. The function for the `short line` would then perhaps be as big as the points?

**Comment by tomusborne** [comment]
This seems to be a bug inside Gutenberg: https://github.com/WordPress/gutenberg/issues/10569

There's no frontend style printed for the short line style.

**Comment by SchneiderSam** [comment]
Ok thanks!
