### ISSUE TITLE
Add options for generate_typography_default_fonts

### ISSUE THREAD

**Issue by addisonhall** [tomusborne/generatepress#84]
I'm looking into the best method for adding fonts to the customizer from external services like Typekit (or even locally hosted) and I'm assuming the best solution is via the generate_typography_default_fonts filter. However I'm finding that I can directly affect the "category" or fallback font. Seems to me that options similar to those in generate_typography_customize_list would be helpful:

```
$fonts[ 'beloved-script' ] = array( 
	'name' => 'beloved-script',
	'variants' => array( '400' ),
	'category' => 'cursive'
);
```

I can use the `generate_typography_customize_list ` filter, but it also adds the fonts to the Google Fonts CSS URL.

**Comment by tomusborne** [comment]
Yes, I agree. That filter needs to be expanded to allow better fallback support.

If you need to add fallbacks, you can do something like this: https://generatepress.com/forums/topic/adobe-typekit-fallback-font/#post-640632

**Comment by addisonhall** [comment]
That never even occurred to me. Thanks, Tom.
