### ISSUE TITLE
Feature - theme options on CPT product attributes page

### ISSUE THREAD

**Issue by inetbiz** [tomusborne/generatepress#87]
I have woocommerce activated. I am creating product attributes to be indexable for material type. I want theme options available while editing so I can choose layout type of full page. The attributes are not used for variations. Just archives enabled to have attribute type pages with all products by that material type. This is an example page https://holylandshopping.com/material-type/olive-wood/

**Comment by inetbiz** [comment]
I also need full page on search results page. Just not sure which page I have to create to do that?

**Comment by tomusborne** [comment]
Per-page metabox options aren't available for archive pages like this in WordPress, unfortunately.

Our Pro version has Layout Elements, which allow you to use the metabox options on non-pages like your archives: https://docs.generatepress.com/article/layout-element-overview/
