### ISSUE TITLE
Fullwidth for the comming container block

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#89]
With Gutenberg 5.2 comes the long-awaited container block (https://github.com/WordPress/gutenberg/pull/13964). It would be great if GeneratePress supports the fullwidth function.  Similar to the pictures.

**Comment by SchneiderSam** [comment]
An update: The Section Block appears at the next Gutenberg Version. It would be nice if Generatepress can join you here: https://github.com/WordPress/gutenberg/pull/13964#issuecomment-472454377

**Comment by SchneiderSam** [comment]
So it's done and merged. But unfortunately only from 5.5 available. Here are some adjustments for theme authors: https://github.com/WordPress/gutenberg/pull/13964#issuecomment-478548896

**Comment by tomusborne** [comment]
Cool! Looks pretty good.

We actually have our own Section block ready to go, which integrates nicely with the way GP does things. We're just waiting on Gutenberg to fix a bug which removes all inner blocks when a container block no longer exists.

**Comment by SchneiderSam** [comment]
That's interesting. So GP is working on own blocks. Well then I'm curious.

**Comment by SchneiderSam** [comment]
Me again. With 5.5 this is now firmly in the core. But I think that GP has to build in a padding. Or? 

![Screenshot_2](https://user-images.githubusercontent.com/9355398/56365557-67eb5780-61f1-11e9-9008-d534bd693226.png)

**Comment by tomusborne** [comment]
GP should add its content padding to the core Group block now as well.
