### ISSUE TITLE
Problems with the new Gutenberg Columns

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#91]
I use Gutenberg 5.7

If I enter 33 in one of my columns, the entire column layout will be destroyed. Since the page is online, I can't show it live. But somewhere there are still problems.

Login: rb
PW: buvexayu
URL: http://b320kx.myraidbox.de/

Normally it should look like this: 
![Screenshot_3](https://user-images.githubusercontent.com/9355398/57794253-85a1d300-7743-11e9-8f58-c69ca5c59a4c.png)

but in the live site it looks like this:
![Screenshot_4](https://user-images.githubusercontent.com/9355398/57794265-8aff1d80-7743-11e9-95ec-f0bf4ed47819.png)

Sounds like an Theme Bug: https://github.com/WordPress/gutenberg/pull/15499#issuecomment-492786103

**Comment by tomusborne** [comment]
Thanks for the heads up! We've removed our custom column spacing in 2.3: https://github.com/tomusborne/generatepress/commit/482d5895bacf400a8c006bb21b66ad1c5da0ccdb

Should be entering alpha soon, but you can go ahead and make those changes to your site now if you'd like.

**Comment by tomusborne** [comment]
2.3 is live. Thanks again for reporting this!
