### ISSUE TITLE
Problems with Gutenberg table and maybe even more?

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#92]
Please check this Page on mobile Device: https://baubeaver.de/schrauben-schraubenarten/

I get a lot of error messages in the console and the table is not responsive at all:

![Screenshot_5](https://user-images.githubusercontent.com/9355398/57859368-15eb2100-77f3-11e9-8dd9-bbfcbda0be3b.png)

**Comment by tomusborne** [comment]
Did you confirm that this was GP related? I'm not seeing anything pointing to GP.
