### ISSUE TITLE
Style-Bug at the block: Text and Media

### ISSUE THREAD

**Issue by SchneiderSam** [tomusborne/generatepress#96]
Hi,

To rebuild:

```
<!-- wp:group {"customBackgroundColor":"#877f7a","align":"wide"} -->
<div class="wp-block-group alignwide has-background" style="background-color:#877f7a"><div class="wp-block-group__inner-container"><!-- wp:heading {"align":"center"} -->
<h2 class="has-text-align-center">Features</h2>
<!-- /wp:heading -->

<!-- wp:media-text {"mediaId":145,"mediaType":"image","imageFill":true} -->
<div class="wp-block-media-text alignwide is-image-fill"><figure class="wp-block-media-text__media" style="background-image:url(https://portal.baubeaver.com/wp-content/uploads/2019/07/wood-411643_1280-1024x768.jpg);background-position:50% 50%"><img src="https://portal.baubeaver.com/wp-content/uploads/2019/07/wood-411643_1280-1024x768.jpg" alt="" class="wp-image-145"/></figure><div class="wp-block-media-text__content"><!-- wp:list -->
<ul><li>lorem ipsum</li><li>lorem ipsum</li><li>lorem ipsum</li><li>lorem ipsum</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:media-text -->

<!-- wp:spacer {"height":43} -->
<div style="height:43px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:media-text {"align":"full","mediaPosition":"right","mediaId":145,"mediaType":"image","imageFill":true} -->
<div class="wp-block-media-text alignfull has-media-on-the-right is-image-fill"><figure class="wp-block-media-text__media" style="background-image:url(https://portal.baubeaver.com/wp-content/uploads/2019/07/wood-411643_1280-1024x768.jpg);background-position:50% 50%"><img src="https://portal.baubeaver.com/wp-content/uploads/2019/07/wood-411643_1280-1024x768.jpg" alt="" class="wp-image-145"/></figure><div class="wp-block-media-text__content"><!-- wp:list -->
<ul><li>lorem ipsum</li><li>lorem ipsum</li><li>lorem ipsum</li><li>lorem ipsum</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:media-text --></div></div>
<!-- /wp:group -->

```

Please note what is displayed in the editor:
![Screenshot_6](https://user-images.githubusercontent.com/9355398/62222641-fd32e600-b3b3-11e9-995f-f74d136f8e01.png)

Frontend:
![Screenshot_7](https://user-images.githubusercontent.com/9355398/62222651-02903080-b3b4-11e9-9f47-462f7976f11d.png)

Neither Full Width nor Wide Width goes to the edge of inside-article. The editor shows that Full Width goes to the edge of the Content Container. But in the frontend it goes to the end of the Browser window.

So I think the setting should be like this:

**Normal:** To the edge of _inside-article_
**Wide Width:** To the edge of the container
**Full Width:** To the edge of the Browser window

**Comment by tomusborne** [comment]
Hi there,

This seems to be happening because you're using `alignwide` and `alignfull` inside a block which is already set to `alignwide` or `alignfull`.

Maybe we need to add some CSS like this:

```
#content .entry-content .alignwide .alignwide, 
#content .entry-content .alignwide .alignfull,
#content .entry-content .alignfull .alignfull,
#content .entry-content .alignfull .alignwide {
    max-width: unset;
    margin-left: unset;
    width: unset;
}
```

**Comment by SchneiderSam** [comment]
Yes, i use a Group Block. And in the Group Block i use two Media & Text Blocks.

If I use your Code nothing happens. :-S

**Comment by tomusborne** [comment]
I guess the question is why are those Media & Text Blocks set to alignwide/full if the parent (Group) block already is? What kind of layout are you going for?

**Comment by SchneiderSam** [comment]
Oh, yeah, now I see what you mean. I come to the edge with my boxes when I ungroup them. But my goal was to set a background color for a certain area. Now the boxes go to the edge, but the background color is missing.

**Comment by tomusborne** [comment]
Did you end up resolving this? It seems like the solution is to avoid those alignment options inside nested blocks vs adding more code to prevent it from happening.
